### ISSUE TITLE
Runtime conditionals

### ISSUE THREAD

**Issue by rheacangeo** [GridTools/gt4py#1]
For backends of 'debug' and 'numpy', runtime conditionals are not implemented (and the error nicely tells you so). A runtime conditional on data can be achieved with vectorized expressions...e.g.  a = q[0, 2, 0]* (c[0,0,0] > 0.0) + q[0, 3, 0] * (c[0,0,0] <= 0.0) to achieve a conditional:
if (c[0,0,0] > 0.0):
  a = q[0,2,0]
else:
  a = q[0,3,0]
It is likely not performant, but works. If I switch the backend to 'gtmc' with this expression I no longer get the same answer -- significant differences, not just roundoff error (changes on the order of 10% seen). The  non-vectorized conditional form of that stencil nicely does not crash with the gtmc backend, but produces the same incorrect answers. It's possible there is an issue with my setup, but I would not expect a dramatic answer change with a change in backend. It is known that the runtime conditionals are future work, I am not insisting this be resolved asap, but wanted to share it as an issue.

**Comment by gronerl** [comment]
It was already for the debug backend. Pull request #2  should implement it for the numpy backend. For your case, it is also possible (and already was possible before) to use numpy conditionals in the form of 
`a = q[0, 2, 0] if c[0,0,0] > 0.0 else q[0, 3, 0]`. 
I'll still have to look into the issue you describe with the MC backend.

**Comment by gronerl** [comment]
I fail to reproduce this, can you provide a minimal example that is failing?

**Comment by rheacangeo** [comment]
This seems to be fixed - - one of my more complex stencils is still getting a different answer with gtmc, but using simple runtime conditionals no longer appears to be the culprit. I will open a new issue if I find the source of the gtmc backend getting a different answer than numpy. Let me know if you would like to see it.
