### ISSUE TITLE
Functional: `FixMissingLocations` sometimes copies location information from wrong nodes

### ISSUE THREAD

**Issue by BenWeber42** [GridTools/gt4py#1015]
Testcase from: https://github.com/BenWeber42/gt4py/commit/b85013a26eec495ac3592b4ad9f8a9c52aeeb91c

```python
def test_sibling_nesting_bug():
    """
    Test for a bug where the location information sometimes wasn't taken from the
    parent node, but from a nested sibling node.
    """
    astree = get_fixed_ast(
        """
        a = (
            1 * 2
            + 3
        )
        """
    )


    assert (
        isinstance(astree.body[0].value.left.op, ast.Mult)
        and astree.body[0].value.left.op.end_lineno == 3
    )
    assert isinstance(astree.body[0].value.op, ast.Add) and astree.body[0].value.op.end_lineno == 4
```
(This testcase will only trigger the bug, after #1014 has been fixed)

`FixMissingLocations` doesn't use a stack to track parent nodes, but a field instead. Because of this, nested children of sibling nodes will overwrite `_parent_node`. Then other children will copy the location information of nested children of their sibling nodes instead of their parent node.

https://github.com/GridTools/gt4py/blob/c63c11eced04a60ef6584788a92b3dc2851a34af/src/functional/ffront/ast_passes/fix_missing_locations.py#L18-L51

**Comment by tehrengruber** [comment]
Resolved in #1020
