### ISSUE TITLE
Functional: Avoid duplicating expressions in `SimpleAssignTargetPass`

### ISSUE THREAD

**Issue by BenWeber42** [GridTools/gt4py#1016]
The `SimpleAssignTargetPass` rewrites assignments such as `a = b = 0` into single assignments. However, in the process, the _right-most hand-side_ will get duplicated multiple times.

This:
```python
<<first assign target>> = <<second assign target>> = <<very big expression>>
```

Will become:

```python
<<first assign target>> = <<very big expression>>
<<second assign target>> = <<very big expression>>
```

To avoid duplicating  `<<very big expression>>`, we could rewrite it instead to:

```python
tmp = <<very big expression>>
<<first assign target>> = tmp
<<second assign target>> = tmp
```
(where `tmp` is a fresh variable name)

https://github.com/GridTools/gt4py/blob/8e9ac25300ac8d4eda920ee206b046ae9edf9d30/src/functional/ffront/ast_passes/simple_assign.py#L50-L80

**Comment by BenWeber42** [comment]
This works well if `<<first assign target>>` is just a symbol, but I'm unsure if it's guaranteed that an assignment target can never be a bigger expression. This might be true now (not sure). But we may want to change that in the future.

I think at the Python AST level, we shouldn't make strong assumptions about what the AST will look like. If we support more general cases, we'll be more flexible at later stages (e.g., dialect parser) in the future. I'm quite afraid of Python AST passes restricting possibilities in the future.

Related: #1017

**Comment by tehrengruber** [comment]
For simplicity of the pass I implemented the temporary approach. Otherwise something like this gets complicated `(b, c) = a = (1, 1)` as the tuple on the left hand side can not copied to the right hand side without modifying the `ctx` field of the `ast.Name` nodes.
