### ISSUE TITLE
Stencil launch overhead

### ISSUE THREAD

**Issue by ofuhrer** [GridTools/gt4py#102]
The launch overhead of gt4py stencils seems to be on the order of 10ms, which is a _lot_. The whole timestep of an atmospheric model should typically take O(100ms) and is launching O(100) stencils, if we are aiming for a throughput of 1 SYPD at 1 km resolution. The plot shows launch overheads of the same stencil running in a) plain python b) gt4py with numpy backend c) gt4py with gtx86 bakckend and d) Fortran.

![image](https://user-images.githubusercontent.com/5963462/87844650-f080f980-c873-11ea-8ada-b1217fbdc42e.png)

**Comment by ofuhrer** [comment]
@jdahm already has a branch for improving this that he will put in a PR. At the sync-meeting of 7/21/20 @egparedes mentioned that he was not sure whether the feature to disable checks and just pass through the pointers already exists in gt4py.

**Comment by havogt** [comment]
TODO: link to recent developments, e.g. FrozenStencil.

**Comment by jdahm** [comment]
#537 and #539 address this.

**Comment by jdahm** [comment]
Those PRs, especially the caching PR (which transparently improves this), reduces the stencil overhead to nearly zero. Even when computing the hash, this is 25x faster than before in my tests.
