### ISSUE TITLE
Scalars become temporaries

### ISSUE THREAD

**Issue by ofuhrer** [GridTools/gt4py#103]
It seems that for the following code...
```Python
with computation(PARALLEL), interval(...):
    b = CONST_A / CONST_B
    c = b * CONST_C
    d = c ** CONST_D
    f = d * ( e[1, 0, 0] - e[-1, 0, 0] )
```
...gt4py makes `b`, `c`, and `d` temporary fields, even though they should be scalars for good performance.

**Comment by DropD** [comment]
This is a known limitation which is planned to be lifted at some point.

**Comment by havogt** [comment]
Just for reference, to anyone who is going to work on this: In the dawn team we defined the parallel model to do exactly what gt4py currently does. The frontend doesn't know local variables, all variables are assumed to be fields. Then it's up to the optimization to transform temporaries to local variables if possible. See https://github.com/MeteoSwiss-APN/dawn/wiki/SIR-Execution-Model.

#59 might addresses that. We should verify that the code above is correctly optimized with #59.

**Comment by havogt** [comment]
It is correct behavior to assume a temporary, but it is optimized back to a scalar.
