### ISSUE TITLE
Function calls with scalar literals do not work

### ISSUE THREAD

**Issue by ofuhrer** [GridTools/gt4py#104]
It seems that passing literal constants to functions does not work, e.g.
```Python
@gtscript.function
def max(x,y):
    if x > y:
        return x
    else:
        return y
...
    with computation(PARALLEL), interval(...):
          out_field = max(5., 10.)
```

**Comment by DropD** [comment]
It is unclear to me, from all I know `@gtscript.function` subroutines are meant for working on fields. They can take scalar constants but in the documentation they only occur as optional arguments (with a default value). Possibly that could work, but there should be a way to use purely scalar functions without having to make them `gtscrip.function`s.

**Comment by ofuhrer** [comment]
This comes from a code which uses the _same_ function once for a scalar and once for a field. It would be awkward to have to implement the same function twice, no?

**Comment by DropD** [comment]
yes, however thinking about performance, you don't want to repeat the same scalar operation for every grid point. So it might make more sense to calculate this outside the stencil and stick it into the externals. Unless the example is simplified and what you really want to do is more dynamic?

**Comment by egparedes** [comment]
To me it looks like the function call with constant arguments makes sense and it should be allowed. In terms of performance, I think an advanced analysis pipeline should be able to detect that this is a constant operation and thus optimize the code without the user caring about it.

**Comment by ofuhrer** [comment]
Agreed. If called with scalar arguments compiler with `-O3` can detect this and evaluate compile time and store the result. Similar to...
```C++
const float pi = 2. * math::asin(1.);
```

**Comment by ofuhrer** [comment]
Note: This is probably related to https://github.com/GridTools/gt4py/issues/103, if the literal arguments are interpreted as temporaries the call would be legal and it would be up to the optimizer to make them scalars.

**Comment by jdahm** [comment]
The following code compiles and generates code that looks correct with the GTC backends, so I'll close this. Let us know if you still have issues and we can re-open.
```python
from gt4py import gtscript
import numpy as np


@gtscript.function
def func(a, b):
    return a + b


@gtscript.stencil(backend="gtc:gt:cpu_ifirst")
def stencil(
    input_field: gtscript.Field[gtscript.IJK, np.int32],
    output_field: gtscript.Field[gtscript.IJK, np.int32],
):
    with computation(PARALLEL), interval(...):
        if input_field > 0.0:
            output_field = func(input_field, 1)
        else:
            output_field = input_field
```
