### ISSUE TITLE
Cannot assign NaN

### ISSUE THREAD

**Issue by ofuhrer** [GridTools/gt4py#105]
It does not seem possible to assign NaN with gt4py, e.g. ...
```Python
a = float("NaN")
b = np.nan
c = math.nan
```
...do not work. A workaround might be `a = 0./0.` but that feels wrong.

**Comment by mbianco** [comment]
There was a discussion about having this as build-in function. Can this be a solution?

**Comment by jdahm** [comment]
Is this still required? It could be a builtin function that always returns a float or double type, but it could be a difficult feature to reign in.

**Comment by ofuhrer** [comment]
This is not a high priority. But for debugging purposes I think it is a useful feature, e.g. a use-case is to initialize a field to NaN to make sure uninitialized values are not being consumed.

**Comment by jdahm** [comment]
Can that be done outside stencils? Seems like it would only be a gt4py concern if it were used in an algorithm.

**Comment by jdahm** [comment]
I did some more reading on the IEEE 754 standard the other day and it doesn't give a single representation of a NaN -- formally it's defined as any (non-zero) mantissa with the exponent set to 255. Of course we could use the standard [numpy.nan](https://numpy.org/doc/stable/reference/constants.html?highlight=nan#numpy.nan), but I'm not certain we can be assured that is the same NaN that all the C++ backends will use. Therefore I would vote that we leave this to the users creating the ndarrays before calling the stencils.

**Comment by jdahm** [comment]
We discussed this in a team meeting and decided that it should be left as the responsibility of the user calling the stencils, instead of something supported inside gt4py. If someone feels differently, they can re-open later.
