### ISSUE TITLE
Cannot use function with return value is inside an if-statement

### ISSUE THREAD

**Issue by ofuhrer** [GridTools/gt4py#106]
This issue is probably related to https://github.com/GridTools/gt4py/issues/52 or even the same issue. If the return value of a function is determined inside an if-statement, we cannot use the function to assign a temporary.
```Python
@gtscript.function
def abs_fn(a):
    if a > 0:
        return a
    else:
        return -a

...
    with computation(PARALLEL), interval(...):
        b = abs_fn(a)
```

**Comment by jdahm** [comment]
Functions now only allow a single return statement, and I believe that resolves this issue.
