### ISSUE TITLE
Type of temporary (and possibly rank and dimensions)

### ISSUE THREAD

**Issue by ofuhrer** [GridTools/gt4py#107]
Currently gt4py infers the type of temporaries from the resulting type of the RHS of the assignement to the temporary. For large stencils with many input / output fields of different type (real, integer, boolean), it feels that we are loosing type checking by not being explicit about the type of temporaries.

Also, as we move gt4py towards being able to deal with fields of different rank with different mapping of the dimensions to the `i, j, k` dimensions, we will probably have to explicitly declare the temporaries, since this can no longer be inferred, e.g.
```Python
c = a[i, j] * b[k]
```
could imply `c[i, j, k]` or simply `c[i, j]`.

**Comment by jdahm** [comment]
Blast from the past! I think we've settled this issue by trying to add typed temporaries.
