### ISSUE TITLE
CUDA backend fails because of symbol names > 11k characters

### ISSUE THREAD

**Issue by ofuhrer** [GridTools/gt4py#108]
When trying to run a complex stencil, the nvcc crashes because the symbol names generated by the `gtcuda` backend exceed the limit of 11k characters.

**Comment by DropD** [comment]
This reminds me of something @gronerl was working on recently. Will check with him when he's back from vacation.

**Comment by havogt** [comment]
This is fixed in CUDA 11.

**Comment by egparedes** [comment]
@gronerl is fixing this in PR #59

**Comment by havogt** [comment]
> @gronerl is fixing this in PR #59

To be more precise, it will just mitigate the problem by removing temporaries and as a side-effect you get shorter symbol names. But for big stencils you might still run into that problem even after that PR. There is no way around that with CUDA < 11.

**Comment by ofuhrer** [comment]
Repeated compilation of sea-ice parametrization (which caused the original problem) again with latest verision of gt4py and issue no longer appeared. I think it's ok to close this issue until we run into the problem again with (even) larger stencils.
