### ISSUE TITLE
Wrong flake8 configuration

### ISSUE THREAD

**Issue by samkellerhals** [GridTools/gt4py#1131]
After the release of Flake 6.0.0 it is invalid to have inline comments in the ignore part of the configuration file, see this issue: https://github.com/PyCQA/flake8/issues/1750

To avoid errors in the future we can easily fix this by not using inline comments to describe the error codes.

The current pattern we are using is the following:

```python
[flake8]
ignore =
   E501  # comment about this error code
```

This can be fixed by doing this instead:

```python
[flake8]
ignore =
   # comment about this error code
   E501,
   # another comment
   E502
```

**Comment by havogt** [comment]
we are on 6.1.0 now, this issue is probably solved
