### ISSUE TITLE
Add support for new Python versions with AST modifications

### ISSUE THREAD

**Issue by egparedes** [GridTools/gt4py#12]
Python 3.8 introduced changes in the Python AST that breaks the current frontend and this may happen again in the future. A new generic version-independent AST could be used to avoid this problems in the future.

**Comment by mbianco** [comment]
How much work is needed to simply adapt the code to support 3.8? What should GT4Py be expected to support in terms of Python versions?

**Comment by havogt** [comment]
3.8 is actually supported now. I'll close this issue.
