### ISSUE TITLE
Bug: Inlining a neighbor_sum into a Koff

### ISSUE THREAD

**Issue by muellch** [GridTools/gt4py#1212]
This is a minimal example of the bug, which results in a compiler error:

```
@field_operator
def _neighbor_sum_into_koff_bug(
    kh_smag_ec: Field[[EdgeDim, KDim], float],
) -> Field[[CellDim, KDim], float]:
    kh_c = neighbor_sum(kh_smag_ec(C2E), axis=C2EDim)
    hdef_ic = kh_c(Koff[-1])
    return hdef_ic
```

See also this icon4py PR: https://github.com/C2SM/icon4py/pull/148

Or specifically this file for a minimal example which can be used for debugging:
https://github.com/C2SM/icon4py/blob/2a750dac2d321a5fa02317d268595ae979eefd0a/atm_dyn_iconam/src/icon4py/atm_dyn_iconam/neighbor_sum_into_koff_bug.py

**Comment by havogt** [comment]
I just tested it with the PR that contains the improved lowering. Seems to be fixed there.
