### ISSUE TITLE
Definition IR nodes do not retain source locations

### ISSUE THREAD

**Issue by DropD** [GridTools/gt4py#122]
The following code snippet shows an assertion failure caused by all location information of top level statements inside the compuation block of a stencil being `None`.

```python
import ast

import numpy as np

import gt4py
import gt4py.frontend
from gt4py import gtscript

def func(in_field: gtscript.Field[np.float_]):
    with computation(PARALLEL), interval(...):
        in_field = in_field + 2.0
        in_field = in_field - 0.5
        in_field = in_field / 0.5
        in_field = in_field * 4.0
        if 4.0 < 5:
            in_field = in_field[0, 0, 1] + in_field[0, 0, -1]
        in_field = 3 if in_field < 4 else 2

options = gt4py.definitions.BuildOptions(name="foo", module="bar")
ir = gt4py.frontend.gtscript_frontend.GTScriptFrontend.generate(func, {}, options)

assert any([s.loc for s in ir.computations[0].body.stmts])
```

I have not yet investigated where the information gets lost, but I suspect it happens in the `GTScriptParser.visit_*` methods.

**Comment by tehrengruber** [comment]
I just ran a quick for `loc=` in the frontend. Apprently the source locations are never added to the Definition IR nodes. An idea would be to have a `NodeVisitor` which by default copies the location of the visited node to the returned node.

**Comment by havogt** [comment]
reopen if there is a strong interest
