### ISSUE TITLE
Finalize error message formatting

### ISSUE THREAD

**Issue by petiaccja** [GridTools/gt4py#1292]
Error messages in gt4py are mainly formatted as a full sentence:
```
module.Error: The IR is at object `name` is invalid because of x and y.
```
Python, however, formats error messages without punctuation:
```
module.Error: the IR at object 'name' is invalid because of x and y
```
We should decide which style, if either of these, we follow, and adjust error messages across the code accordingly.

**Comment by havogt** [comment]
Done in #1386
