### ISSUE TITLE
Python backends compatibility with GT model

### ISSUE THREAD

**Issue by jdahm** [GridTools/gt4py#130]
Certain features (such as horizontal offsets in a stage) are not flagged in the python backends, but are not allowed in the GridTools backends because they break the consistency model. The toolchain should do a better job of catching these before backend compilation to ensure feature consistency when developing with a python backend.

**Comment by egparedes** [comment]
This seems related to #69

**Comment by jdahm** [comment]
Yes. We just added #148 with frontend checks. Should there also be some backend checks to complement those? #121 had something to that effect, but we removed that PR in favor of frontend checks.

**Comment by jdahm** [comment]
Agreed. Once the parallel model discussion in https://github.com/GridTools/concepts/wiki/GTScript-Parallel-model is finished it would be great to have a check that ensures that in the frontend, so we don't write code with `debug` or `numpy` and see that it causes `static_assert`s with GT backends.

**Comment by jdahm** [comment]
The situation has improved with the pydantic validators in the GTC toolchain. I'll close this for now, but we should open issues if we see particular instances where gridtools throws a static assert (that GTC did not catch).
