### ISSUE TITLE
Use non-cryptographic hash functions for fingerprinting

### ISSUE THREAD

**Issue by egparedes** [GridTools/gt4py#139]
I propose to use fast non-cryptographic hash algorithms in the current implementation of `shash` (meaning _stable/string/source/ any-other-s-word_ hash), which are not only fast but also more appropriate for fingerprinting. 

I suggest to use the python bindings (https://github.com/Cyan4973/xxHash) to xxHash project (https://cyan4973.github.io/xxHash/), which seem to be the most efficient and up-to-date python and c implementations.

**Comment by havogt** [comment]
Still relevant?

**Comment by egparedes** [comment]
Still relevant but mostly a small and not very important optimization. I think it can be safely close.
