### ISSUE TITLE
Support custom GridTools source folders in the gt_src_manager

### ISSUE THREAD

**Issue by egparedes** [GridTools/gt4py#141]
Move the repo configuration to entries in the `config` module instead of harcoded values. Since the code generation is customized to a specific GridTools version, the source manager should still check that the provided repo has a compatible version (check with @havogt which strategy should be used for this check: same major/minor? same major and equal or higher minor? ...)

Also add basic tests to test this component.

**Comment by havogt** [comment]
This is supported, currently user responsibility to point to appropriate versions.
