### ISSUE TITLE
Document possible incompatibilities with user installed GridTools

### ISSUE THREAD

**Issue by DropD** [GridTools/gt4py#15]
## Problem
If a user has previously installed GridTools (C++ libs) in a standard prefix (like /usr/local) then it is possible that during setuptools.build_ext the compiler will find those headers. Namely if
* the python version being used was compiled using includes from the same prefix
* boost is installed in the same prefix

This is a problem if the user installed GridTools is a different version from what GT4Py uses and there are breaking changes, like different header structure.

## Solution
* document the GidTools version requirement for GT4Py and advise users to (re-) install other versions of GT C++ to a separate prefix

## Luxury solution
* get actual include paths used for compilation and scan them for existing gridtools sources at gt4py.gt_src_manager install time, decide to give an error message or use the existing sources if compatible

**Comment by egparedes** [comment]
Updated docs in latest commit (ea39cd4).
