### ISSUE TITLE
Cannot install GT sources

### ISSUE THREAD

**Issue by SpiderMonkey1975** [GridTools/gt4py#16]
When I try installing the GT library sources using the command: **_pip3 install ./gt4py/setup.py install_gt_sources_**, I get the following error:

WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
Defaulting to user installation because normal site-packages is not writeable
ERROR: Invalid requirement: './gt4py/setup.py'
Hint: It looks like a path. It does exist.

This worked previously so I don't know why it has stopped working.  I am trying to install on my local laptop running Ubuntu 18.04 and I am using Python 3.6.9.

Any assistance would be appreciated.

Thanks,
Mark

**Comment by egparedes** [comment]
The command to install GT sources has changed recently. The new way to do it is quickly mentioned in the README file:
```
# Run the command to install GridTools C++ sources
python -m gt4py.gt_src_manager install
```
We will add a reference to this installation mechanism also in the quickstart guide to avoid further misunderstandings.

**Comment by egparedes** [comment]
The quickstart guide has been updated so I'm closing this issue.
