### ISSUE TITLE
Dawn backends: Vertical intervals

### ISSUE THREAD

**Issue by stubbiali** [GridTools/gt4py#160]
Dawn seems to mistreat any vertical interval whose lower-bound is specified as a negative number. Consider this simple operator:
```python3
def average(in_field: gtscript.Field[float], out_field: gtscript.Field[float]):
    with computation(PARALLEL): 
        with interval(0, 1):
            out_phi = 0.
        with interval(1, -1):
            out_phi = 1.
        with interval(-1, None):
            out_phi = 2.
```
It will set the last two layers to `2.`, instead of just the very last layer as expected. The same stencil works fine with any non-Dawn backend.

**Comment by havogt** [comment]
obsolete
