### ISSUE TITLE
Guiding gt4py users

### ISSUE THREAD

**Issue by jdahm** [GridTools/gt4py#167]
Even when https://github.com/GridTools/gt4py/issues/143 is fixed by putting statements into different multistages, there will be a performance penalty. The way around this performance penalty is to use a functional-like form, creating a new variable for the output. While more localized changes can be made internally by the toolchain, this is a refactor that the user would likely need to do, since calling code would need to be changed fairly significantly depending on the context. It could be nice for users to have a stencil keyword that when enabled, would lint and let them about bad practices or suggest such refactoring that would increase performance.

**Comment by DropD** [comment]
I like the idea of that. Are you thinking of analysis passes adding metadata explaining why a potential optimization was disabled, which can be used to give specific information about a stencil definition? Or of a separate set of heuristics giving more general advice?

**Comment by jdahm** [comment]
I was originally thinking a set of heuristics giving general advice, but I like your idea of adding metadata to explain why optimizations were disabled too. So far it's just an idea, so perhaps we should try out one of these approaches to explain why statements are split into separate multistages after #169 is merged.

**Comment by jdahm** [comment]
I'm going to close this issue for now and re-open as "Rewrite gtscript frontend with user-first focus"
