### ISSUE TITLE
Field boundary/extent analysis with parallel/horizontal regions present

### ISSUE THREAD

**Issue by jdahm** [GridTools/gt4py#170]
@twicki Recently found an unintuitive behavior with regions that is a problem worth discussing.

First, the example:

```python
from gt4py import gtscript
import gt4py.storage as gt_storage

@gtscript.stencil(rebuild=True, backend="debug")
def copy_stencil(in_storage: gtscript.Field[float], out_storage: gtscript.Field[float]):
    from __splitters__ import j_start

    with computation(PARALLEL):
        with interval(...):
            out_storage = 2
            with parallel(region[:, j_start : j_start + 1]):
                out_storage = in_storage[0, 2, 0]

shape = (1, 10, 10)
in_storage = gt_storage.ones(shape=shape, default_origin=(0, 0, 0), dtype=float, backend="debug")
out_storage = gt_storage.zeros(shape=shape, default_origin=(0, 0, 0), dtype=float, backend="debug")
copy_stencil(in_storage, out_storage, origin=(0, 1, 1), domain=(1, 8, 8), splitters={"j_start": 0})
```

This raises an exception with the message `Compute domain too large (provided: (1, 8, 8), maximum: (1, 7, 9))`.

This is natural because the extent analysis (done at compile time) is not taking into account the `j_start` value at run-time. So `field_info["in_storage"] = ((0, 0), (0, 2), (0, 0))`, so the maximum `J` domain size is `7` instead of `8`.

I see a few ways to resolve this in the long term (and short term fixes), including:
1. Add boundary/extent analysis for each stage, and loop over these at run time, looking at the values of the splitters when needed. This means more python code checks at run-time, which we may not want.
2. Skip extent analysis for ApplyBlocks that are restricted by a parallel region, regardless. This is a bit unsafe, but keeps most of the extent analysis.
3. Skip extent analysis altogether for stencils with at least one parallel region.

Thoughts on these approaches?

**Comment by DropD** [comment]
Not sure myself but I will get someone who knows this better to look at it.

**Comment by egparedes** [comment]
Thanks for describing the issue and starting a discussion on the topic. I think option 2 is a reasonable compromise between safety and overhead/complexity. However, I wonder if it is not possible to detect at compile time (or let the user flag) which horizontal regions don't span outside of the computation domain, so the analysis on those regions can be also kept.

**Comment by jdahm** [comment]
@egparedes sounds good. I'll make that change to the PR soon, and will close this issue when that is done.

**Comment by jdahm** [comment]
@egparedes I just pushed a commit to the regions PR that does this. Can you check if `d23f2cb` implements that skip correctly?

**Comment by jdahm** [comment]
As far as I can tell this is implemented in `regions-gdp-impl`, so I'll close this for now.
