### ISSUE TITLE
Statement/Stage Reordering

### ISSUE THREAD

**Issue by jdahm** [GridTools/gt4py#171]
#169 introduces a fix for the horizontal race condition issue, but as a result it breaks certain solver patterns, including the first and last statement in the computation below, which only make sense in the same multistage. GT4Py must reorder the statements first to ensure they remain in the same multistage.
```python
    with computation(FORWARD):
        with interval(...):
            tmp = out_storage[0, 0, -1]
            ##
            tmp2 = mid_field[1, 0, 0]
            mid_field = 1
            ##
            out_storage = 2 * tmp
```

We should try to catch certain patterns like this and reorder the statements so the greedy algorithm correctly and efficiently splits stages and multistages.

**Comment by mbianco** [comment]
Isn't this related to the parallel model?

**Comment by jdahm** [comment]
@mbianco Yes, I would say this is a good example to run through in the parallel model discussion.

**Comment by mbianco** [comment]
This also seems the standard compiler reordering problem (this is similar also to the Tomasulo's algorithm, right?), it should be fairly easy to implement with some compiler knowledge.

**Comment by havogt** [comment]
In the current parallel model, the example is forbidden.
