### ISSUE TITLE
ComputeExtentsPass fails on domains without sequential axis

### ISSUE THREAD

**Issue by DropD** [GridTools/gt4py#182]
This currently appears as a bug, since domains without sequential axis are supported by the `Domain` constructor as well as some passes like `MergeBlocksPass` checking for presence of a sequential axis explicitly.

If that case really has no potential use case, `Domain` should not allow it and all checks should be removed.
If we want to continue supporting it, we need to fix `ComputeExtentsPass`.

**Comment by havogt** [comment]
Probably the fix is

>Domain should not allow it and all checks should be removed.

**Comment by jdahm** [comment]
The GTC backends currently bake in the concept that there's always IJK present. I believe we are deprecating and removing the legacy backends, so I'll close this for now. Let me know if you'd like to re-open.
