### ISSUE TITLE
Add def_ir and iir to stencil object

### ISSUE THREAD

**Issue by jdahm** [GridTools/gt4py#207]
We are building a tool for data flow analysis, and naturally want to include the stencils as a sub-tree of nodes in the data flow diagram. When the parser comes across a stencil call, e.g. `stencil` like this:

```python
def compute(...):
    stencil(...)
```

as far as I can tell it actually has no way of getting back to the implementation IR from both the live object and Python AST node. There is no information stored in the StencilObject about the method it came from, nor the build info. Since it exists anyway, could we just always store this info in the StencilObject instead of passing it out as a key in the `build_info` dictionary argument?

**Comment by jdahm** [comment]
I should note that we can work around this for now with hacks in our application, but it would be nice to have this soon in gt4py as a whole, since the data exists, but it's not quite in the right place.

**Comment by egparedes** [comment]
It looks like a reasonable request, although I'm not quite sure if it's very useful to access ImplementationIR right now. Note that StencilOobject stores a reference to the actual definition function in `StencilOobject.definition_func`

**Comment by jdahm** [comment]
Thanks @egparedes.

> Note that StencilOobject stores a reference to the actual definition function in StencilObject.definition_func

That's good to know. Actually `definition_func._gtscript_` does store the full annotation including externals and nonlocals captured at the time, so it is possible to re-lower to IIR from there. That said, we still opted to create out own wrapper class for now, that exposes the `build_info`.

![Screen Shot 2020-10-06 at 9 05 11 AM](https://user-images.githubusercontent.com/68032/95227539-1226b880-07b3-11eb-91e5-7f025bc15a99.png)

I would therefore consider this low priority then for now, but if @DropD or you are refactoring that portion of the frontend, we would support removing `build_info` in favor of adding it to the StencilObject.

**Comment by gronerl** [comment]
Is this still relevant? The issue could be updated with GTC IR's. But is the original motivation still applicable? Otherwise, I propose to close.

**Comment by jdahm** [comment]
I wanted this for a custom dataflow library at one point, but now that we've centered around DaCe, I think we can close this.
