### ISSUE TITLE
Optional fields in GTCUDA

### ISSUE THREAD

**Issue by stubbiali** [GridTools/gt4py#211]
The `generate_pre_run` and `generate_post_run` methods of `GTCUDAPyModuleGenerator` do not check if the info attached to a field are `None`, i.e. if the field is specified as an optional argument in the definition function and it's actually not needed in the computations. Although the fix is quite trivial, I'm opening an issue to signal the lack of a proper unit test for this.

**Comment by egparedes** [comment]
Good catch! We clearly need to create a test case for this, but I also wonder when this bug appear since it was working fine before. Maybe we broke it during the backend refactoring. @DropD could you take a look at it when you have some time?

**Comment by stubbiali** [comment]
Since https://github.com/GridTools/gt4py/commit/95e564faff8bb5f89196a178b690b20780729e38 field info are retrieved from `args_data` rather than `module_info`. That could be the root cause.
