### ISSUE TITLE
TypeError: Optional[t] requires a single type.

### ISSUE THREAD

**Issue by jdahm** [GridTools/gt4py#214]
Using `typing` wrappers like `Optional`, `Callable`, etc. in python code (calling stencils) does not work with field types like  `Field[float, IJK]` because
```python
    return _FieldDescriptor(dtype, axes)
```
returns an instance, rather than a type itself. Do we want to have support for these wrapper types?

Here is the function that raises the exception `raise TypeError(f"{msg} Got {arg!r:.100}.")`

```python
def _type_check(arg, msg, is_argument=True):
    """Check that the argument is a type, and return it (internal helper).

    As a special case, accept None and return type(None) instead. Also wrap strings
    into ForwardRef instances. Consider several corner cases, for example plain
    special forms like Union are not valid, while Union[int, str] is OK, etc.
    The msg argument is a human-readable error message, e.g::

        "Union[arg, ...]: arg should be a type."

    We append the repr() of the actual value (truncated to 100 chars).
    """
    invalid_generic_forms = (Generic, _Protocol)
    if is_argument:
        invalid_generic_forms = invalid_generic_forms + (ClassVar, )

    if arg is None:
        return type(None)
    if isinstance(arg, str):
        return ForwardRef(arg)
    if (isinstance(arg, _GenericAlias) and
            arg.__origin__ in invalid_generic_forms):
        raise TypeError(f"{arg} is not valid as type argument")
    if (isinstance(arg, _SpecialForm) and arg not in (Any, NoReturn) or
            arg in (Generic, _Protocol)):
        raise TypeError(f"Plain {arg} is not valid as type argument")
    if isinstance(arg, (type, TypeVar, ForwardRef)):
        return arg
    if not callable(arg):
        raise TypeError(f"{msg} Got {arg!r:.100}.")
    return arg
```

**Comment by mcgibbon** [comment]
It looks like this should be implemented as a user-defined generic type. A generic type is a type that takes in arguments (like `Dict[key_type, value_type]`. https://docs.python.org/3/library/typing.html#user-defined-generic-types

**Comment by jdahm** [comment]
I'm not sure this one is easily resolvable during the Christmas cleanup without changing the interface. The core problem is that our Field interface is not very clean: you can give it e.g. `Field[float]` or `Field[IJK, (float, (2,))]`. If we make Field a generic, it needs to take a set number of arguments, unless we use variadic generics https://www.python.org/dev/peps/pep-0646/ but that is only approved for 3.10...

**Comment by tehrengruber** [comment]
I discussed this with @egparedes a while ago and we came to the conclusion that it is not meaningful to fix this until we have found a good way that is also compatible with type checking. The unclean interface puts further insult to inquiry. Variadic generics are, beside the pep still being in draft state, not a real solution as both the axes as well as the dimension are of variable length. Using `Tuple[I, J, K]` and Tuple[Literal[2], Literal[2]] (2x2 matrix) does work in principle - even today -, but this is way to verbose. My best take right now is to have a `Field` class inheriting from `Generic` that overrides `__class_getitem__` which internally converts all tuples into `Tuple` types, literals into `Literal` types and then write a small plugin for mypy. With respect to the original issue here: `Optional[Field[...]]` like type hints mainly occur outside of stencil codes with very few exceptions. In this case the workaround is to just quote the expression. With static type checking not working anyway the downsides are minimal.

**Comment by jdahm** [comment]
@tehrengruber Agreed. I want to close this for now as a "won't fix" until there is a new frontend with an actual type that is compatible with type checking.

**Comment by mcgibbon** [comment]
> Tuple[Literal[2], Literal[2]] (2x2 matrix)

This is the type hint for an argument which only accepts `(2, 2)`. The type hint for a 2 by 2 matrix using tuples of e.g. int would be `Tuple[Tuple[int, int], Tuple[int, int]]`. `List[List[int]]` for lists does not require or allow you to specify a length for the dimensions.

**Comment by tehrengruber** [comment]
@jdahm Agreed.
@mcgibbon In isolation yes absolutely, what I mean here is transforming our current syntax `Field[IJK, (float, (2,2))]` into `Field[IJK, Tuple[float, Tuple[Literal[2], Literal[2]]]]` (not suggesting we should do this).
