### ISSUE TITLE
Functions with no return values are not caught

### ISSUE THREAD

**Issue by twicki** [GridTools/gt4py#233]
```python
@gtscript.function
def foo(in1, in2):
    in1 = in2


@gtscript.stencil(backend="numpy")
def copy_stencil(in_storage: Field[float], out_storage: Field[float], val: float):
    with computation(FORWARD):
        with interval(...):
            out_storage = foo(in_storage, out_storage)
            in_storage = 1
```
currently this code compiles but behaves very strangely:
the line with the function call gets silently dropped

**Comment by egparedes** [comment]
This is clearly a bug because such a function definition without return values is illegal. There are different ways to deal with this, but I guess the simplest one would be to raise an error in the function definition if they do not return a value.

**Comment by jdahm** [comment]
I just tried this and it triggers an error in the gtscript frontend.
