### ISSUE TITLE
Stages and ApplyBlocks

### ISSUE THREAD

**Issue by jdahm** [GridTools/gt4py#235]
A Stage currently includes a list of `ApplyBlock`s in the IIR, but if a Stage has multiple `ApplyBlock`s, the GT backends fail to compile because they define multiple `apply()` methods for the structs.

They should be refactored to hold a single ApplyBlock when migrating to the Eve platform.

**Comment by jdahm** [comment]
This affects #234. In that PR I'm going to attempt a change that merges all ApplyBlocks together (those that only differ by a parallel interval definition).

**Comment by egparedes** [comment]
I don't really understand this issue: IIRC a stage may have different apply blocks, given they are defined in different vertical intervals. There could be a problem only if there are several apply blocks are they are not restricted to a specific vertical interval.

**Comment by havogt** [comment]
I agree. You can have multiple apply blocks, but they must not overlap in the vertical intervals (and I think they need to be contiguous).

**Comment by jdahm** [comment]
This issue was due to a misunderstanding. It came up when adding parallel regions to ApplyBlocks, so two ApplyBlocks had the same vertical interval, but different parallel intervals. Since then I've moved the parallel interval out of the ApplyBlock (it was the wrong place anyway), so this is no longer an issue.
