### ISSUE TITLE
Support function calls as arguments to functions

### ISSUE THREAD

**Issue by jdahm** [GridTools/gt4py#248]
Return values from functions calls seem to not be supported as arguments to function calls themselves (#247 improves the error message). Should this be supported in the future? Presumably this would be a fairly minor change in the frontend only.

**Comment by egparedes** [comment]
I agree with this idea, as I mentioned in the comments of #247 . If you are willing to implement this feature, I would skip #247 and wait for the PR with the implementation.

**Comment by jdahm** [comment]
Should be solved together with https://github.com/GridTools/gt4py/issues/520.
