### ISSUE TITLE
Wrong field bounds in stencil field_info

### ISSUE THREAD

**Issue by tehrengruber** [GridTools/gt4py#284]
There appears to be a bug in the creation of the `field_info` attribute of the stencil object for the `K`-axis. The following code raises in `IndexError` exception inside the debug backend, but should already trigger before any backend code is called in `_validate_args` alla `ValueError: Compute domain too large`.

```python
@gtscript.stencil(backend=backend, **backend_opts)
def fluxdiv(
    in_fzh  : gtscript.Field[dtype],
    out_div : gtscript.Field[dtype]
):
    with computation(PARALLEL), interval(...):
        out_div = (in_fzh[0,0,1]-in_fzh[0,0,0])


nx, ny, nz = 2, 2, 2

in_fzh = gt.storage.zeros(backend=backend, dtype=dtype, shape=(nx+1, ny+1, nz), default_origin=(0, 0, 0))
out_div = gt.storage.zeros(backend=backend, dtype=dtype, shape=(nx, ny, nz), default_origin=(0, 0, 0))
fluxdiv(in_fzh,out_div,origin={"in_fzh": (1, 1, 1), "out_div": (1, 1, 1)},domain=(nx-1, ny-1, nz-1))
```

**Comment by jdahm** [comment]
I believe you meant that it should error with `domain=(nx-1, ny-1, nz)`. The latest `StencilObject._validate_args` catches this.
