### ISSUE TITLE
BlockMergerPass changes semantics

### ISSUE THREAD

**Issue by gronerl** [GridTools/gt4py#294]
Currently, tests fail if the BlockMergerPass is deactivated (namely vertical advection cpp regression tests) This indicates that this pass actually changes the semantics of the IR, while it should only be for optimization.  

In fact, this happens to avoid the problem exposed in #293.

**Comment by gronerl** [comment]
this probably has to be fixed at the same time as #293

**Comment by gronerl** [comment]
possibly related: #246

**Comment by havogt** [comment]
old pipeline...
