### ISSUE TITLE
gt4py.gt_src_manager not working wor GT2

### ISSUE THREAD

**Issue by gronerl** [GridTools/gt4py#323]
the gt_src_manager seems not to work with the gridtools 2 sources and issues a warning:
```
(gt4py) gronerl@tower-ubuntu:~$ python -m gt4py.gt_src_manager install
/usr/lib/python3.8/runpy.py:127: RuntimeWarning: 'gt4py.gt_src_manager' found in sys.modules after import of package 'gt4py', but prior to execution of 'gt4py.gt_src_manager'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
GridTools sources are installed
```
i.e. with the instructions in the README.md it is not currently possible to run the gtc backends.

**Comment by fthaler** [comment]
I can confirm the warning, but installation works flawlessly. You have to pass the version you want to install, use `python -m gt4py.gt_src_manager install  --major-version 2` to install GT2 required for GTC.

**Comment by gronerl** [comment]
Thanks, I would say then it's not so urgent, but we should still update the README.md

**Comment by egparedes** [comment]
There is now a PR #325 to update the docs

**Comment by egparedes** [comment]
PR merged. Closing this issue
