### ISSUE TITLE
Validation failure on GPU

### ISSUE THREAD

**Issue by stubbiali** [GridTools/gt4py#348]
I have a stencil in my code which validates for any CPU backend, but fails on GPU, either using `gtcuda` or `gtc:gt:gpu`. The stencil is rather lengthy, but it can be stripped down to
```python3
@gtscript.stencil(backend="gtcuda")
def test_stencil(in_field: gtscript.Field[float], out_field: gtscript.Field[float]):
    with computation(PARALLEL), interval(...):
        out_field = (
            in_field[0, +2, 0] + in_field[0, -2, 0]
            - 4.0 * (in_field[0, +1, 0] + in_field[0, -1, 0])
            + 6.0 * in_field[0, 0, 0]
        )
```
If `in_field` is uniform, the stencil should compute zeros. But validation fails if `in_field` is filled with `0.08333333333333529` (catched through Hypothesis).

**Comment by havogt** [comment]
I get something of order `1e-17`, do you expect an exact `0`?

**Comment by stubbiali** [comment]
I forgot to mention that `out_field` is scaled by a certain factor in the original stencil. So `1e-17` is surely acceptable per se, but can lead to a substantial discrepancy if the factor is large. I'm not surprised by this - common scenario with floating points. But curious (or maybe not so unexpected?) that it only occurs on GPU. CPU backends produce exactly zero.

**Comment by stubbiali** [comment]
Sorry, forget about this. I erroneously thought that this issue could affect my simulations too, but it doesn't actually. My bad. I will increase the tolerance in my tests to make them pass on GPU. I'm going to close if nobody objects.

**Comment by egparedes** [comment]
Sure, go ahead and close it.
