### ISSUE TITLE
Round-trip to json fails due to enums

### ISSUE THREAD

**Issue by gronerl** [GridTools/gt4py#352]
serializing gtc nodes to json and deserializing does not work
```Python
json = oir.json()
Stencil.parse_raw(json)
```
with erros such as
```
E   vertical_loops -> 4 -> loop_order
E     Invalid value type [expected: <enum 'LoopOrder'>, received: <class 'str'>] (type=type_error)
```
This seems to be the solution:
https://stackoverflow.com/questions/65209934/pydantic-enum-field-does-not-get-converted-to-string/65211727#65211727

this currently prevents saving and loading sdfgs.

**Comment by tehrengruber** [comment]
Fixed in #612
