### ISSUE TITLE
Code generation not deterministic

### ISSUE THREAD

**Issue by ofuhrer** [GridTools/gt4py#374]
Code generation uses unsorted dicts (e.g. temporaries), which leads to different code being generated upon each invocation of code generation. We should probably agree that it is our goal to have code generation be deterministic and implement changes in the code generation in order to make it so.

**Comment by egparedes** [comment]
Is this issue already fixed by #357 or do you think more fixes are needed?

**Comment by ofuhrer** [comment]
No, that probably addresses these issues. Would it make sense to add a test to make sure that generated code is reproducible, if that's easy enough?

**Comment by egparedes** [comment]
Yes, that makes sense. We should have added the test in that PR, actually.

**Comment by jdahm** [comment]
Is this still an issue?

**Comment by ofuhrer** [comment]
Shouldn't there be a unit test (or several) making sure this is the case?

**Comment by jdahm** [comment]
Yes, this should be up to each backend to ensure. I'm not sure it's easy to come up with a test for this, but it should be fixed if we see anything come up from application usage and watch backend changes to ensure it doesn't slip in.

Now that dicts are implicitly ordered the only remaining way this could happen (not counting malicious-intent `random` calls) is through the use of (unordered) sets in backends.

**Comment by havogt** [comment]
I agree, that's probably very hard to test in general.
