### ISSUE TITLE
Inconsistent results when working around self-assignment with temporary

### ISSUE THREAD

**Issue by gronerl** [GridTools/gt4py#432]
This stencil 
```python
def corner_ut(
    ut: Field[np.float64]
):

    with computation(PARALLEL), interval(...):
        ut_tmp = ut
    with computation(PARALLEL), interval(...):
        ut = ut_tmp[1, 0, 0] + ut_tmp[1, 1, 0] + ut_tmp[0, 1, 0]

```
Has different behavior on all GT C++ based backends (GTC and old) than on other backends. (debug, numpy, gtc:dace). (GPU not tested)

The generated code properly splits the two assignments into separate horizontal executions:
```python
        return multi_pass(
            execute_parallel().stage(HorizontalExecution140442380790272(),
                                     ut_tmp, ut),
            execute_parallel().stage(HorizontalExecution140442380326128(), ut,
                                     ut_tmp));
      };
```
The error looks as follows:
reference:
```[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 3. 3. 3. 3. 3. 3. 1.]
 [1. 3. 3. 3. 3. 3. 3. 1.]
 [1. 3. 3. 3. 3. 3. 3. 1.]
 [1. 3. 3. 3. 3. 3. 3. 1.]
 [1. 3. 3. 3. 3. 3. 3. 1.]
 [1. 3. 3. 3. 3. 3. 3. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]
```
output of `gtc:gt:cpu_ifirst`
```[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 3. 3. 7. 3. 3. 3. 1.]
 [1. 3. 3. 7. 3. 3. 3. 1.]
 [1. 3. 3. 7. 3. 3. 3. 1.]
 [1. 3. 3. 7. 3. 3. 3. 1.]
 [1. 3. 3. 7. 3. 3. 3. 1.]
 [1. 3. 2. 4. 1. 2. 2. 1.]
 [1. 1. 1. 1. 0. 1. 1. 0.]]
```
 
 Only workaround I found so far is making ut_tmp an API field, which is inconvenient.

**Comment by gronerl** [comment]
note that the result even spills into the halo.

**Comment by fthaler** [comment]
As discussed in the standup today, this is expected GridTools behavior. There is no global sync between stages within a `multi_pass` call. A correct GT implementation would consist of two computations with `tmp` being a normal field (non-temporay in the sense of GridTools).

**Comment by rheacangeo** [comment]
I just ran into this as well with this exact example stencil and was just about to open an issue, thanks for looking into it, so great you already saw it.  It is quite common in atmospheric science for a user to want to update a field based on adjacent input values. I understand the global sync idea, what I don't understand is how q would be changed outside of the specified origin and domain.  
A reproducer
`def add_offset_stencil(q: FloatField):
    with computation(PARALLEL), interval(...):
        qtmp = q
    with computation(PARALLEL), interval(...):
        q = qtmp[-1, 0, 0] + 1.0

 shape = (7, 7, 3)
 q = make_storage_from_shape(shape)
 q[:] = 1.0
 q_ref = make_storage_from_shape(shape)
 q_ref[:] = 1.0
 origin = (3, 3, 0)
 domain = (1, 1, 3)
 q[2, 3, 0] = 5.0
 q_ref[2, 3, 0] = 5.0
 q_ref[3, 3, 0] = 6.0
`
When calling the stencil on q, q[3, 3,0] should be changed, to be q[2, 3, 0] + 1 = 6
This gets the correct answer, but q[2, 3, 0] is changed back to be 1.0 when this stencil is called.
I could understand if q[3, 3, 0] got the wrong answer, if it read qtmp[2, 3, 0] before it was copied, but why would it change at an index that is only being read? qtmp would need to expand the origin and domain it is computed on, but why would q change?

**Comment by gronerl** [comment]
Issue was duplicated in #887 which was fixed by raising an error in #888 Personally I would prefer that this should work anyways, just not crating a gt-transient under the hood.

**Comment by gronerl** [comment]
I can confirm that neither making ut_tmp an API field nor making one of the two computations sequential pass by the frontend currently.

**Comment by havogt** [comment]
https://github.com/GridTools/concepts/pull/53

**Comment by havogt** [comment]
added to doc
