### ISSUE TITLE
Incorrect results with K-Caching in the GtCpp backends

### ISSUE THREAD

**Issue by eddie-c-davis** [GridTools/gt4py#454]
The `fv3core` implementation in `gt4py` has exposed an issue with the k-caching implementation in the GTCpp code generation of the GTC toolchain. Here is an example of a stencil that reproduces this issue:

```python
def set_initial_vals(gam: Field[IJK, float], delp: Field[IJK, float]):
    with computation(FORWARD):
        with interval(0, 1):
            grid_ratio = delp[0, 0, -1] / delp
            gam = 0.5 * grid_ratio
        with interval(1, -1):
            grid_ratio = delp[0, 0, -2] / delp[0, 0, -1]
            bet = 2.0 + grid_ratio - gam[0, 0, -1]
            gam = grid_ratio / bet
        with interval(-1, None):
            gam = 1.0
```
The `KCacheDetection` pass identifies `gam` and `delp` as candidates for k-caching. The generated code appears to be correct, with the possible exception of the last stage, that writes `delp0` even though `delp` is not used there,
```c++
    eval(delp0()) = eval(delp());
    eval(gam0()) = static_cast<double>(1.0);
    eval(gam()) = eval(gam0());
```
Perhaps this is required for proper flushing?

The concerning issue is that  at k-level 2 (the second iteration of the second interval), the `gam` field contains `NaN` values.

```
CPUStorage([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
            [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
            [ 0.,  0., nan, nan, nan, nan,  0.,  0.],
            [ 0.,  0., nan, nan, nan, nan,  0.,  0.],
            [ 0.,  0., nan, nan, nan, nan,  0.,  0.],
            [ 0.,  0., nan, nan, nan, nan,  0.,  0.],
            [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
            [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])
```

The same stencil with k-caching disabled produces valid data.

The attached tar file contains the following files using the `gtc:gt:cpu_ifirst` backend:

[set_initial_vals-kcaching-reproducer.tar.gz](https://github.com/GridTools/gt4py/files/6779798/set_initial_vals-kcaching-reproducer.tar.gz)

1. This file is a reproducer script in python (`set_initial_vals.py`)
2. The generated code with k-caching enabled (`set_initial_vals-wkcache-computation.hpp`)
3. And finally, the generated code without k-caching (`set_initial_vals-nokcache-computation.hpp`)

Thank you, and please let me know if you require additional information.

**Comment by fthaler** [comment]
Is the example code correct? I could not really reproduce the issue, things fail independently of k-caches. And the reason is that there is an out-of-bounds access on the first and second levels. That is, `delp[0, 0, -1]` in `grid_ratio = delp[0, 0, -1] / delp` and `delp[0, 0, -2]` in `grid_ratio = delp[0, 0, -2] / delp[0, 0, -1]` are out of bounds on the first and second level respectively. If I shift the `delp` indices by one, it seems to work here.

**Comment by eddie-c-davis** [comment]
Thank you @fthaler for the excellent observations. I believe this issue can be closed.

**Comment by fthaler** [comment]
Perfect. Please note that issue #570 still was a problem for me on the fixed code. Hopefully we can fix that one soon.
