### ISSUE TITLE
validation error for legal statement

### ISSUE THREAD

**Issue by rheacangeo** [GridTools/gt4py#459]
Currently this pattern throws an error with all fields as API fields:
```python
 with computation(PARALLEL), interval(...):
        vt = u * dx
        ut = v * dy
       vorticity = rarea * (vt - vt[0, 1, 0] - ut + ut[1, 0, 0])
```
```
return gtir.VerticalLoop(
pydantic/main.py:362: in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for VerticalLoop
E  __root__
E   Illegal write and read with horizontal offset detected for {'ut', 'vt'}. (type=value_error)
```
It does not throw an error if you add a computation
```python
 with computation(PARALLEL), interval(...):
        vt = u * dx
        ut = v * dy
 with computation(PARALLEL), interval(...):
       vorticity = rarea * (vt - vt[0, 1, 0] - ut + ut[1, 0, 0])
```

We believe both should be legal because API fields get extended. The behavior for both should be the same. When ut and vt are temporary fields, both patterns work.

**Comment by tehrengruber** [comment]
Indeed this should be legal, here is a more reduced example:
```python
@stencil(backend=backend, **backend_opts)
def mystencil(fxh : gtscript.Field[dtype]):
    with computation(PARALLEL), interval(...):
        tmp = fxh[1,0,0]
        fxh[0,0,0] = fbc_x * tmp
```

**Comment by havogt** [comment]
This is illegal according to our last iteration of the execution model. https://github.com/GridTools/concepts/pull/39. I am happy to contribute to discussions to change that, but I will not drive such discussions.

> [...] because API fields get extended.
I don't understand this statement.

The reason for this restriction is that this code needs to be executed in 2 separate kernels (in blocking backends, i.e. all fast backends) to avoid race conditions.

**Comment by rheacangeo** [comment]
The compressed example from tehrengruber is a race condition that we are aware is illegal, but the issue presented here is not.  Read with an offset after write does not break the execution model in concepts 39. The API fields should be computed in an extended domain after analyzing how they are used (e.g. read with an offset below). ut and vt are computed as they same value throughout the domain no matter which block sets it first. Thus no matter which block runs the adjacent cell the same answer should be present for ut and vt at an offset. 
We can discuss more whether this is legal. But regardless, the behavior should be consistent among the different ways to write it (with or without an extra computation, with API fields or temporaries)

**Comment by rheacangeo** [comment]
Sorry, didn't mean to mess with your labeling, wanted to see if it worked. I'll let you relabel it if you agree this is a bug. It seems so to me.

**Comment by havogt** [comment]
Right, makes sense. Currently, https://github.com/GridTools/concepts/pull/39 doesn't allow this, but I agree it can be allowed without problems. (Assuming extent analysis works properly.) I'll merge https://github.com/GridTools/concepts/pull/39 and apply this change as a PR.

**Comment by havogt** [comment]
I opened this PR https://github.com/GridTools/concepts/pull/42.

**Comment by rheacangeo** [comment]
Awesome, thank you!

**Comment by jdahm** [comment]
> The compressed example from @tehrengruber is a race condition that we are aware is illegal, but the issue presented here is not. 

The example @tehrengruber presented uses a temporary variable, while in the original example presented `ut` and `vt` are API fields.

**Comment by rheacangeo** [comment]
You're right -- it's a confusing situation that API fields and temporary fields have different behavior. My intention was to say we understand that read after write with an offset is unsafe (if only a rule for API fields), while this issue is about read with an offset after write on center.

**Comment by havogt** [comment]
This is not allowed in the current parallel model, please reopen if there is a proposal how to extend the parallel model to make this legal.
