### ISSUE TITLE
Use of SymbolTables is inconsistent in GTC backends

### ISSUE THREAD

**Issue by jdahm** [GridTools/gt4py#478]
The GTC backend passes have a pattern that simply takes the `node.symtable_` from the top-level node and passes that as a keyword argument to all children visitor methods. This works when the IRs have a single symbol table, but in reality none of them do, because `common.BlockStmt` derives from `SymbolTableTrailt`.

When adding a `For` node that defines a local `ScalarDecl` for the counter, we are running into the problem that the `gtir_dtype_resolver` is failing because the symbol table used there (from the top-level) does not contain the for loop counter's `ScalarDecl`.

**Comment by DropD** [comment]
The best solution would be to make the visitor automatically add the symbol table to the keywords if it exists on the node. If the node has one but already gets one from higher up, it should pass on a chain map with it's own table at the end.
