### ISSUE TITLE
Strange results/possible race condition with GridTools v2

### ISSUE THREAD

**Issue by jdahm** [GridTools/gt4py#489]
The following two GridTools sources are nearly the same, except that one contains some extra statements that update `u` and `v` (and hence also adds a few more `inaccessor`s).

```python
...
    with computation(PARALLEL), interval(...):
        ubt = (ub + vt) * rdx
        fy = u * rdx
        gy = fy * ubt
        vbt = (vb - ut) * rdy
        fx = v * rdy
        gx = fx * vbt

        if (kinetic_energy_fraction_to_damp > dcon_threshold) or calculate_dissipation_estimate:
            u2 = fy + fy[0, 1, 0]
            du2 = ubt + ubt[0, 1, 0]
            v2 = fx + fx[1, 0, 0]
            dv2 = vbt + vbt[1, 0, 0]
            dampterm = heat_damping_term(
                ubt, vbt, gx, gy, rsin2, cosa_s, u2, v2, du2, dv2
            )
            heat_source = delp * (
                heat_source - 0.25 * kinetic_energy_fraction_to_damp * dampterm
            )

        if __INLINED((d_con > dcon_threshold) or calculate_dissipation_estimate):
            with horizontal(region[local_is : local_ie + 1, local_js : local_je + 1]):
                heat_source_total += heat_source
                if __INLINED(calculate_dissipation_estimate):
                    dissipation_estimate -= dampterm

        with horizontal(region[local_is : local_ie + 1, local_js : local_je + 2]):
            if damp_vt > dcon_threshold:
                u += vt
        with horizontal(region[local_is : local_ie + 2, local_js : local_je + 1]):
            if damp_vt > dcon_threshold:
                v -= ut
```

[computation.hpp](https://github.com/GridTools/gt4py/files/7102688/computation.txt)
[computation_with_u_v_updates.hpp](https://github.com/GridTools/gt4py/files/7102689/computation_with_regions.txt)

The problem is that when the `u` and `v` updates are included, our unit testing framework indicates that `heat_source_total` fails to get updated correctly. It's as if the statement `heat_source_total += heat_source` only evaluates at some locations, or fills in some garbage data.

If, on the other hand, the updates of `u` and `v` at the end are commented out, then `heat_source_total` is correctly computed, but of course `u` and `v` are not updated...

**Comment by havogt** [comment]
Please provide a complete debuggable example.
Did you try different backends?
What happens if you remove the u and v updates in the generated code?

**Comment by jdahm** [comment]
That is my intention. I have not gotten to this yet, but placed this here to remind me. Anyway it will still be on a PR branch, since the `horizontal-regions-gtcpp` branch has not been merged yet.

**Comment by jdahm** [comment]
Yes, we haven't gone back to this one but should soon because it really bothered me at the time.
