### ISSUE TITLE
Using a runtime float as both a condition and inside the conditional

### ISSUE THREAD

**Issue by rheacangeo** [GridTools/gt4py#49]
A stencil with a conditional that triggers off a runtime float variable, and is also used in the condition, triggers an error. 
For example:
>@gtscript.stencil(backend="numpy")
>def cap_var(q:  gtscript.Field[_dtype], b:  gtscript.Field[_dtype], q_max: float):
>     if q > q_max:
>             b = q_max 

triggers an Assertion error in the merge_extents method
 def _merge_extents(self, refs: list):
        result = {}
        params = set()
    
        # Merge offsets for same symbol
        for name, extent in refs:
            if extent is None:
               assert name in params or name not in result
               AssertionError

usr/src/gt4py/src/gt4py/analysis/passes.py:359: AssertionError

**Comment by jdahm** [comment]
The following code seems to compile and the generated code looks correct with the GTC backends, so I'll close for now. Let us know if there's still a problem and we can re-open it.

```python
from gt4py import gtscript
import numpy as np


@gtscript.stencil(backend="gtc:gt:cpu_ifirst")
def stencil(
    input_field: gtscript.Field[gtscript.IJK, np.int32],
    output_field: gtscript.Field[gtscript.IJK, np.int32],
    q_max: np.int32,
):
    with computation(PARALLEL), interval(...):
        if input_field > q_max:
            output_field = q_max
        else:
            output_field = input_field
```
