### ISSUE TITLE
kfirst backend SID issue

### ISSUE THREAD

**Issue by jdahm** [GridTools/gt4py#492]
The following test case that should work fails with `std::domain_error: incompatible strides, expected unit stride` on the `master` branch.

```python
from gt4py import gtscript
import gt4py.storage as gt_storage
import numpy as np

backend = "gtc:gt:cpu_kfirst"

INT32_VEC2 = (np.int32, (2,))


def stencil(
    input_field: gtscript.Field[gtscript.IJK, np.int32],
    output_field: gtscript.Field[gtscript.IJK, INT32_VEC2],
):
    with computation(PARALLEL), interval(...):
        output_field[0, 0, 0][0] = input_field


default_origin = (0, 0, 0)
full_shape = (1, 1, 1)
input_field = gt_storage.ones(backend, default_origin, full_shape, dtype=np.int32)
output_field = gt_storage.zeros(backend, default_origin, full_shape, dtype=INT32_VEC2)

gtscript.stencil(definition=stencil, backend=backend)(input_field, output_field)
assert output_field[0, 0, 0, 0] == 1
```

The difference between the `gtc:gt:cpu_ifirst` and `gtc:gt:cpu_kfirst` backends in the bindings are that the `0`s in the `as_sid` template in the `ifirst` backend are `2` in the `kfirst` backend to refer to the unit stride `I` axis index.

```c++
            gt::sid::shift_sid_origin(
                gt::as_sid<std::int32_t, 3, gt::integral_constant<int, 1>, 0>(
                    input_field),
                input_field_origin),
            gt::sid::shift_sid_origin(
                gt::as_sid<std::int32_t, 4, gt::integral_constant<int, 2>, 0>(
                    output_field),
                output_field_origin),
```

The failure is on [this line](https://github.com/GridTools/gridtools/blob/1578948c7cf3a5368126f289d89cabb2af9c0bf4/include/gridtools/storage/adapter/python_sid_adapter.hpp#L47) in `python_sid_adapter.hpp`.

@anstaf

**Comment by anstaf** [comment]
Some comments on `as_sid` usage: the forth template parameter is for optimization. It should be set if it is known in compile time (generation time) which dimension is the innermost (has the stride always equal to 1). My guess (I am not familiar with the python code) that something is wrong here: https://github.com/GridTools/gt4py/blame/cad39952bf339e4762dea77312bc8288275756a2/src/gt4py/backend/gtc_backend/common.py#L24  (github blames @havogt as an author) The quick fix is not to set the forth `as_sid` parameter at all.

**Comment by havogt** [comment]
This is a problem with the specific array shape. If you have size one in a dimensions, the stride is not well defined. For the specific example, we would expect strides `(1,1,1,1)` (in number of elements), but buffer protocol makes it a `(2,2,2,1)`. But with that our check fails. A possible solution would be to skip the check on the C++ side if the dimension of the expected unit stride has size 1.

**Comment by havogt** [comment]
Here is the problem https://github.com/numpy/numpy/blob/7b22284af25279a9332947d024066c0cb43ef25a/numpy/core/src/multiarray/buffer.c#L511 (and comment above). If we have a buffer that cannot be distinguished from a c-layout as in the code above, numpy recalculates the strides as if they were c-layout. See also, https://numpy.org/devdocs/release/1.8.0-notes.html#npy-relaxed-strides-checking.
Therefore, the only solution is to disable the check for stride 1 in case the dimension has size 1.

**Comment by jdahm** [comment]
Ah ok this makes sense. I suppose the problem now is that when we generate the code we don't know if either the storages or stencil compute domain will have unit strides.

**Comment by jdahm** [comment]
I wrote a python module and script today that prints out the shape and strides both in  (using the `strides` attribute) and through the buffer protocol in C++ in order to better understand this. I thought I would share the results because they nicely demonstrate the issue.

For each case below the data type is `(int, (5,))`

shape `(2, 3, 4)`
```
backend: gtc:gt:cpu_kfirst
shape: 2 3 4 5 
python strides: 96 32 8 192
c++ strides: 96 32 8 192 

backend: gtc:gt:cpu_ifirst
shape: 2 3 4 5
python strides: 8 256 64 768
c++ strides: 8 256 64 768 
```

shape `(1, 1, 1)`
```
backend: gtc:gt:cpu_kfirst
shape: 1 1 1 5
python strides: 8 8 8 8
c++ strides: 40 40 40 8 


backend: gtc:gt:cpu_ifirst
shape: 1 1 1 5
python strides: 8 64 64 64
c++ strides: 8 64 64 64 
```

In the case of singleton dimensions, the `cpu_kfirst` backend buffer's protocol has the unit stride on the additional dimension (in array-of-structures fashion) instead of striding the extra dimensions last. There is perhaps little we can do about this while using numpy to allocate the buffers and create the buffer protocol.

**Furthermore, even if we were to avoid the error, this would not resolve the problem, because the numpy array indexing will access elements differently than the gt4py backend will. The current behavior is the only correct, sane behavior.**

I find it particularly interesting that the python strides do not match the buffer protocol in all cases. From playing with this utility, the unit stride dimension is not the one that the backend expects whenever the python strides do not match those from the buffer protocol (you alluded to this earlier). The rules under which I can get them to match are not entirely clear, e.g. with `(2, 1, 1)` the python and c++ strides do not match, but with `(2, 2, 1)` they do.

Should we consider having GridTools allocate the storages in gt4py and return a buffer protocol back to python using the pybind11 utilities? That way we could ensure that the data dimensions go last, and we ensure that the strides and layout are those that GridTools thinks are best for the backends. This might sound complicated, but it actually isn't that bad. [This](https://jakevdp.github.io/blog/2014/05/05/introduction-to-the-python-buffer-protocol/) post walks through implementing one using the C bindings, and could be made even simpler using the `pybind11::buffer_protocol` object described [here](https://pybind11.readthedocs.io/en/stable/advanced/pycpp/numpy.html).

**Comment by havogt** [comment]
There is no real issue here, we only need to work around the check in the buffer protocol SID adapter by dispatching on the size of the (supposed to be) unit stride dimension.

**Comment by gronerl** [comment]
Because I got tagged here, I'll just add that I agree with Hannes. These strides are essentially to be considered undefined because they don't matter. So we need to just exclude these cases from the check, which needs to be done in the SID adapters in the C++ GridTools repository.

**Comment by anstaf** [comment]
C++ PR is ready for review: https://github.com/GridTools/gridtools/pull/1651
