### ISSUE TITLE
multiple 'ands' in a conditional without parenthesis 

### ISSUE THREAD

**Issue by rheacangeo** [GridTools/gt4py#51]
I had a conditional with 3 terms joined by 'ands' -- 
> elif a > 0.0 and q > 0.0 and b < q

But this gave the wrong answer (did not go into the conditional when it should have) until I added parenthesis:
> elif a > 0.0 and (q > 0.0 and b < q)

Perhaps there is something incorrect about chaining ands like that without marking the order?

**Comment by gronerl** [comment]
Thanks for the report, can you try with the fix please?

**Comment by gronerl** [comment]
@rheacangeo

**Comment by rheacangeo** [comment]
Sorry for my delay in responding -- I tried it out and it works perfectly now. Thanks a bunch!
