### ISSUE TITLE
Support variable vertical offsets in dace expansion

### ISSUE THREAD

**Issue by jdahm** [GridTools/gt4py#517]

**Comment by jdahm** [comment]
@eddie-c-davi,s @gronerl - is this still an issue?

**Comment by eddie-c-davis** [comment]
Yes @jdahm, I believe this is still needed. I have a hacky version that validates in the `develop-v37` branch, but it will likely not work in orchestrated mode.

**Comment by jdahm** [comment]
@gronerl is this still an issue?

**Comment by gronerl** [comment]
This is now supported.
