### ISSUE TITLE
Fix support for field offset arguments to functions

### ISSUE THREAD

**Issue by jdahm** [GridTools/gt4py#520]
Offsets to functions seem to not be supported in gtscript, but would be immensely helpful in certain instances. Consider this reproducer:
```python
from gt4py import gtscript
import numpy as np


@gtscript.function
def func(a):
    return a


@gtscript.stencil(backend="gtc:gt:cpu_ifirst")
def stencil(
    input_field: gtscript.Field[gtscript.IJK, np.int32],
    output_field: gtscript.Field[gtscript.IJK, np.int32],
):
    with computation(PARALLEL), interval(...):
        output_field[0, 0, 0] = func(input_field[-1, 0, 0])
```

**Comment by havogt** [comment]
Can you add an example?

**Comment by jdahm** [comment]
Added it!

**Comment by gronerl** [comment]
I think the issue in the example es a different one. In fact, the problem is caused by the `[0, 0, 0]` index on the left hand side. In fact, the example also fails to compile if the assignment is 
`output_field[0, 0, 0] = func(input_field)`
However either of the following compiles:
```
output_field = func(input_field[-1, 0, 0])
output_field = func(input_field+1)
```
