### ISSUE TITLE
Support for more MATH_BUILTINS

### ISSUE THREAD

**Issue by leuty** [GridTools/gt4py#525]
The hyperbolic tangent (tanh) is used, e.g., in two-moment microphysics in ICON

**Comment by leuty** [comment]
Actually, sinh and cosh are needed as well

**Comment by havogt** [comment]
Let's collect all required math functions in a single issue.

**Comment by havogt** [comment]
gamma function (similar to math.gamma of python) #527

**Comment by havogt** [comment]
support for cubed root (cbrt) #526
