### ISSUE TITLE
temporaries inside of conditionals

### ISSUE THREAD

**Issue by rheacangeo** [GridTools/gt4py#54]
Related to #52, we are thinking it might be reasonable to turn off the check for temporaries inside of conditionals, e.g. make the user responsible if they end up with a read before write. 
if a > 0.
   b = 1.
else:
   b = 2.

This triggers the temporaries error even though it is defined in all pathways. I am not suggesting you try to determine whether a new temporary is defined in all pathways, but rather could let the user figure it out. Perhaps the errors would be hard to understand when they did mess it up. 

In many programming languages you can have a variable that is only defined in a certain condition, and if outside that condition. 
if cond:
   f = 1.

...
if cond:
f = f + 1

There may be barriers to this I am not thinking of.

**Comment by jdahm** [comment]
In the GTC backends this condition seems to have been relaxed. The following code snippet compiles and the generated code looks correct, so I'll close this. Let us know if you still have problems and we can re-open.
```python
from gt4py import gtscript
import numpy as np


@gtscript.function
def abs_fn(a):
    b = a
    return b


@gtscript.stencil(backend="gtc:gt:cpu_ifirst")
def stencil(
    input_field: gtscript.Field[gtscript.IJK, np.int32],
    output_field: gtscript.Field[gtscript.IJK, np.int32],
    q_max: np.int32,
):
    with computation(PARALLEL), interval(...):
        if input_field > q_max:
            tmp = input_field
            output_field = abs_fn(tmp)
        else:
            output_field = input_field

```
