### ISSUE TITLE
DaCe horizontal merging pass recurses seemingly forever

### ISSUE THREAD

**Issue by jdahm** [GridTools/gt4py#558]
This pass should be temporarily turned off and fixed. At the same time `dace` should be made an optional extra for `gt4py`.

**Comment by jdahm** [comment]
Example: If the `oir_pipeline` is not passed in https://github.com/ai2cm/sw_solver/pull/3/files#diff-64cfffb694ca9471cd0675bd17d0caf644ca32e6669627dc9c5b7298dedf5ff7R79 and this test is run with `pytest`, then the framework fails to produce a stencil.

**Comment by leuty** [comment]
I think I see a similar issue in my physics code.
