### ISSUE TITLE
Remove deprecated legacy backends

### ISSUE THREAD

**Issue by jdahm** [GridTools/gt4py#566]
The GTC toolchain is now very mature and has only a few minor bugs to iron out. It implements the parallel model very well. The legacy toolchain is no longer maintained, and does not clearly implement the parallel model. In the next release of GT4py let's remove the old code.

When doing this, we need to also remove the `dawn4py` integration since it was only ever integrated with the legacy backends.

Steps:
- [x] Disable tests and unregister backends (#620)
- [x] Remove unused backend files
- [x] Remove unused tests
- [x] Move references to `gt_backends.py` and other legacy files to better locations
- [x] Remove GridTools1 from the source manager and update regression tests to use GridTools2 sources
- [x] Remove `gtc:` prefix on GTC backends.
- [x] Move definition IR into frontend directory.

**Comment by gronerl** [comment]
I propose we also remove the `gtc:` prefix from all backend names.

**Comment by jdahm** [comment]
Yes, agreed 🎉 ! I was going to do that in a separate branch after this one.

**Comment by jdahm** [comment]
Yes, agreed 🎉 ! I added it to the list above.

**Comment by jdahm** [comment]
This is done!
