### ISSUE TITLE
Nested if statements with offset on condition in the numpy backend

### ISSUE THREAD

**Issue by leuty** [GridTools/gt4py#568]
Consider the following snippet from the 1-M microphysics of ICON (gscp_graupel):

```
with computation(FORWARD), interval(kstart, None):

    [700 LOC]

    if k_idx != ke: #k_idx is an index field containing the index of the level (np.arange), ke the index of the last level

        [10 LOC]

        if qr[0, 0, +1] <= zqmin:  # DL: Segfault
            zvzr = 0.0
```

The snippet will pass in the debug backend, since that backend generates "real" IF statements. In the numpy backend, however, the snippet will segfault, since both IF statements are converted into np.where(). The second `where` does not address the offset at `ke`.

**Workaround**
```
with computation(FORWARD), interval(kstart, -1):

        [700 LOC]

with computation(FORWARD), interval(-1, None):
        [the same 700 LOC]

        [10 LOC]

        if qr[0, 0, +1] <= zqmin:  
            zvzr = 0.0
```
The `[700 LOC]` can be turned into a `gtscript.function`, but it is not a long-term solution for more complicated cases.

**Comment by jdahm** [comment]
Does this also fail with the gtc backends?

**Comment by leuty** [comment]
@jdahm 

As soon as i add `if qr[0, 0, +1] <= zqmin`, I get:
```
    raise InvalidSDFGEdgeError("Memlet subset out-of-bounds",
dace.sdfg.validation.InvalidSDFGEdgeError: Memlet subset out-of-bounds (at state graupel_two_state, edge qr[0:__I, 0:__J, 30:__K + 1] (qr:None -> VerticalLoop_140362432494128:IN_qr))
```

**Comment by jdahm** [comment]
Thanks for checking that!

We get quite a few of those in FV3/pace as well. I'm going to make a PR to gt4py that turns off the DaCe merging pass by default until we can sort out these issues.

**Comment by leuty** [comment]
> Thanks for checking that!
You are welcome. Thanks for the quick response.

> We get quite a few of those in FV3/pace as well.
Yea. I would not be surprised if this motive was ubiquitous across models.

@stubbiali 
I guess IFS will have it as well, right? Maybe even in `cloud_sc`?

**Comment by stubbiali** [comment]
Thanks @leuty for raising the issue and @jdahm for taking care of it! I haven't looked at IFS-FVM and CLOUDSC in much detail yet, but it's reasonable to assume that they also have some of these cases.

**Comment by havogt** [comment]
Here is a simple reproducer, as expected it doesn't work for `gtc:numpy` and I believe this is correct behavior. We should describe this better and try to catch such errors.

The rule would be: You are not allowed to reference out-of-bounds elements within an interval.

Intervals are solving exactly this problem, they allow us to make optimizations that are much harder in the general `if` on domain indices.

```
import numpy as np

from gt4py import gtscript
from gt4py import storage as gt_storage
from gt4py.gtscript import FORWARD, computation, interval
from gtc.passes.oir_dace_optimizations.horizontal_execution_merging import (
    graph_merge_horizontal_executions,
)
from gtc.passes.oir_pipeline import DefaultPipeline


# backend = "gtc:numpy"
backend = "numpy"

dtype = np.float64


@gtscript.stencil(backend=backend, rebuild=True, oir_pipeline=DefaultPipeline(skip=[graph_merge_horizontal_executions]))
def issue_568(in_field: gtscript.Field[dtype], kindex: gtscript.Field[gtscript.K, int], ke: int, out_field: gtscript.Field[dtype]):
    with computation(FORWARD):
        with interval(...):
            if kindex != ke:
                out_field = in_field[0,0,1]


if __name__ == "__main__":
    N = 30
    shape = [N] * 3
    origin = (0, 0, 0)

    in_data = np.fromfunction(lambda i, j, k: k, shape)
    out_data = np.zeros(shape)
    index_data = np.asarray(range(N))

    in_storage = gt_storage.from_array(in_data, backend, default_origin=origin, dtype=dtype)
    out_storage = gt_storage.from_array(
        out_data,
        backend,
        default_origin=origin,
        dtype=dtype,
    )
    index_storage=gt_storage.from_array(index_data, backend, default_origin=(origin[-1],), dtype=int, mask=[False,False,True])

    issue_568(in_storage, index_storage, N-1, out_storage)

    assert all(out_storage[0, 0, k] == 1.0 + k for k in range(N-1))
```

**Comment by havogt** [comment]
Did you put the 700 lines in a function, I believe that is the best solution that we have for now.

**Comment by havogt** [comment]
From @tehrengruber: a workaround could be to add a padding k layer to the problematic field(s).

**Comment by havogt** [comment]
We came to the conclusion that the original code example is not legal and we should give an error. Is this covered in your current work @tehrengruber ?

**Comment by tehrengruber** [comment]
Yes this will throw an error at execution time in the future.

**Comment by jdahm** [comment]
Is this issue resolved then?

**Comment by tehrengruber** [comment]
@jdahm Yes #597 resolves this and throws an error for the initial example here in all gtc based backends.

@leuty In FVM-LAM boundary conditions are treated using seperate stencil calls restricted to the respective boundary parts so we don't have this problem. Due to the significant performance penality this is not recommended though and is an artefact originating elsewhere.

To summarize the issue:
The initial example is forbidden and should be treated using `interval`. If the stencil is more complicated and using `interval` results in code duplication this is a strong sign that the stencil should be refactored such that the code that is independent of the k-index resides in a separate function. With respect to porting codes to GT4Py this is certainly cumbersome, but increases readability, and helps the toolchain to understand the stencils structure. A workaround is to artificially increase the shape of the field in the k-dimension and for the sake of safety initialize the values to `math.nan`. However this should, if at all, only be used temporarily.
