### ISSUE TITLE
K-caching code generation issue with `GTC:CUDA` backend

### ISSUE THREAD

**Issue by eddie-c-davis** [GridTools/gt4py#580]
The code generation for k-caches as detected by the `KCacheDetection` OIR pass exhibits some interesting (and incorrect) behavior on the following reproducer stencil.

Reproducer stencil:
```python
backend = "gtc:cuda"
GRAV = 9.80665


def fv_subgridz_init(gz: FloatField, delz: FloatField):
    with computation(PARALLEL), interval(...):
        gzh = 0.0
    with computation(BACKWARD), interval(0, -1):
        gz = gzh[0, 0, 1] - (0.5 * GRAV) * delz
        gzh = gzh[0, 0, 1] - GRAV * delz
```

The `KCacheDetection` pass identifies the `gzh` temporary as k-cacheable:
```python
KCache(name='gzh', fill=True, flush=True)
```

The `CUIRCodegen` class generates scalar temporaries from `gzh1m1000` to `gzh1p1000`,
```c++
    double gzh1m1000;
    double gzh1m999;
    double gzh1m998;
    ...
    double gzh1p998;
    double gzh1p999;
    double gzh1p1000;
```

followed by the corresponding staggered assignments in the backward `VerticalLoopSection`:
```c++
for (int _k_block = k_size + -1 - 1; _k_block >= 0; --_k_block) {
      ...
      gzh1p1000 = gzh1p999;
      gzh1p999 = gzh1p998;
      gzh1p998 = gzh1p997;
      ...
      gzh1m997 = gzh1m998;
      gzh1m998 = gzh1m999;
      gzh1m999 = gzh1m1000;
}
```
It is uncertain whether this code is the cause, but the generated code does not validate, while the `gtc:gt:gpu` backend does produce correct data.

Artifacts can be found in the tar file at this GDrive [location](https://drive.google.com/file/d/19IbFQifaU5BGwEbaj-beRjPRUgRcbxCK), including:

1. Serialize field data (`fvsubgridz_init_repro.npz`)
2. Validating `gtc:cuda` generated code without k-caching (`fv_subgridz_init-gtccuda-computation-nokcache.hpp`)
3. Incorrect `gtc:cuda` generated code with k-caching (`fv_subgridz_init-gtccuda-computation-wkcache.hpp`)
4. Correct `gtc:gt:gpu` generated code with k-caching (`fv_subgridz_init-gtcgtgpu-computation-wkcache.hpp`)

Thank you!

**Comment by fthaler** [comment]
Thanks for reporting. Please try PR #581. Looks like this bug was introduced with variable k-offsets. I just tried compilation locally though, please let me know if this PR really fixes the issue.

**Comment by eddie-c-davis** [comment]
Thank you very much @fthaler, I shall give #581 a try!
