### ISSUE TITLE
Make dace an optional dependency

### ISSUE THREAD

**Issue by jdahm** [GridTools/gt4py#594]
Once #571 is merged, we can make dace an optional dependency. This would make `dace` an extra for gt4py, and if it's not present the `gtc:dace` backend will not be registered.

**Comment by jdahm** [comment]
@egparedes, @havogt, How would you like tests (unit and suites) to work with dace as an optional dependency?

Options:
1. Disable the backend instead of raising an exception at [suites.py:306](https://github.com/GridTools/gt4py/blob/master/src/gt4py/testing/suites.py#L306)
2. Test independently in another repo (gtc-dace?)

If we go with option (1) then we probably want to enable the dace extra for tests.

Currently dace is both a backend, as well as a portion of the toolchain (though disabled by default). We can also use this opportunity to remove the optimization pass if you'd like.

If only a backend, ideally we would start to decouple backends from the optimizer and frontend, so we can drive the testing time down. This will however improve somewhat naturally when the legacy backends are removed.

**Comment by havogt** [comment]
Not sure, I fully understand option 1. I would like to have all dace stuff tested by default in CI, i.e. we should make sure it's extra-installed for all CI jobs. But if it's not installed, why is the backend enabled anyway? Is that in the tox settings?

> Currently dace is both a backend, as well as a portion of the toolchain (though disabled by default). We can also use this opportunity to remove the optimization pass if you'd like.
No, let's keep it separate.

>If only a backend, ideally we would start to decouple backends from the optimizer and frontend, so we can drive the testing time down. This will however improve somewhat naturally when the legacy backends are removed.
What do you mean by decouple?
