### ISSUE TITLE
HorizontalExecutionMerging has O(n^2) complexity.

### ISSUE THREAD

**Issue by gronerl** [GridTools/gt4py#599]
The current HorizontalExecutionMerging (and both previous Horizontal Execution merging passes) create HorizontalExecution OIR nodes at each merging step. Creating this node has linear complexity in the number of nodes of the created HorizontalExecution due to the validators. If `n` horizontal executions are merged into one, Horizontal executions of increasing size are created and validated, only to be discarded at the next step, leading to complexity of `O(n^2)` overall.

This issue leads to a prohibitively long pipeline runtime of e.g. the [satadjust](https://github.com/ai2cm/fv3core/blob/master/fv3core/stencils/saturation_adjustment.py#L554-L896) stencil of fv3core where the pass is running for hours.

The issue can be resolved by instead of creating new HorizontalExecution node's each step, collect the body of the result in a list and only at the end of the pass creating the HorizontalExecution node.

**Comment by havogt** [comment]
@jdahm Do you understand all details of the problem? Is it just an intrinsic pydantic problem, i.e. the field type validation are already a problem (because it creates new object all the time) or only the additional validators (the ones created with `@validator`)?

**Comment by jdahm** [comment]
Hi @gronerl

Thanks for reporting!

> due to the validators

Definitely agreed that certain stencils in FV3 take _forever_ to compile through the toolchain, but as far as I can tell, `oir.HorizontalExecution` does not have any validator directly on it (thought `oir.AssignStmt` has some). Which validators are you referring to? Have you noticed that higher-level validators (e.g. those on `oir.Stencil` trigger when mutating some of these objects in the tree?

**Comment by gronerl** [comment]
To be honest, I haven't investigated too much.

All child nodes are reused, except for the `.body` attribute which is just a list catenation of existing nodes, so it has to be caused at this level. I just realized that when putting a progress bar with tqdm, mergings became more and more expensive as the merging go on, and my proposed fix resolves the performance issue. So I just assumed that some linear-time work is at hand when creating the `oir.HorizontalExecution`.  I haven't done any further investigation to verify this though.

**Comment by egparedes** [comment]
I suspect @gronerl  might be right about the `O(n^2)` complexity caused by pydantic. AFAIK, older versions of pydantic recreated the full tree every time a new node was created instead of just reusing/assigning the passed child nodes. Therefore, even without taking validation into account (and there is always validation for the types of the attributes at least) this would lead to a routine with quadratic complexity.

I don't know if recent pydantic versions have changed this behavior but this issue alone was already the main reason why I tried to move away from pydantic to datamodels. I suggest to run a quick test to verify that child nodes are still not reused when creating a new node; that is, creating a new parent node takes longer when the child nodes are deep trees than when they are shallow trees.

**Comment by jdahm** [comment]
In that case the PR I made doesn't address the problem, because it creates a `TempHorizontalRegion` outside `gtir` for the sake of merging. I'll close that one for now until we can find a better solution.

**Comment by gronerl** [comment]
I propose to just remove the inheritance from (Node) and instead make it a normal `dataclass`. Then, #600 should be the fix.

**Comment by jdahm** [comment]
I thought about doing that, but unfortunately then the `AccessCollector` does not work with it, since that only accepts `TreeNode`. We could make a custom `xiter` (on the list of body stmts) and change `AccessCollector` to accept it, but that was more work.

**Comment by fthaler** [comment]
Simple local fix available at #605. Not very elegant but seems to work (tests still running, so no guarantee yet).

**Comment by jdahm** [comment]
Nice, I see you were able to get around it by the order of operations. Good catch!
