### ISSUE TITLE
stencil failure with gtmc that works for numpy

### ISSUE THREAD

**Issue by rheacangeo** [GridTools/gt4py#6]
Hello! I have specified a stencil that works with the numpy backend, but not gtmc. It appears too break because it's a long stencil, and can be fixed by using temporary variables. 
Here is the problem stencil:
```
@gtscript.stencil(backend=backend, rebuild=True)
def mystencil(uc: sd, vc: sd, ut: sd, vt: sd, cosa_u: sd, cosa_v: sd):
    with computation(PARALLEL), interval(0, None):
        damp_u = 1. / (1.0 - 0.0625 * cosa_u[0, 0, 0] * cosa_v[-1, 0, 0])
        ut[0, 0, 0] = (uc[0, 0, 0]-0.25 * cosa_u[0, 0, 0] * (vt[-1, 1, 0] + vt[0, 1, 0] + vt[0, 0, 0] + vc[-1, 0, 0] - 0.25 * cosa_v[-1, 0, 0] * (ut[-1, 0, 0] + ut[-1, -1, 0] + ut[0, -1, 0]))) * damp_u
```
This gives: 
GRIDTOOLS ERROR=> Horizontal extents of the outputs of ESFs are not all empty. All outputs must have empty (horizontal) extents

   48 |                 GT_STATIC_ASSERT(extent_t::iminus::value == 0 && extent_t::iplus::value == 0 
I don't quite know what this means..

It works if I break this long stencil into several functions.

**Comment by gronerl** [comment]
This stencil has a field on both the target and value side of the assignment. This is undefined behavior right now, and we need to take a decision at some point whether we want to not allow this (and print a meaningful error for all backends)  or work around it by automatically adding temporaries.  This decision depends on the outcome some of the ongoing discussions around the design of the top-level IRs.
Note that this is not specific to the "gtmc" backend but applies to all compiled backends.

**Comment by egparedes** [comment]
Related to #65

**Comment by havogt** [comment]
Illegal self-assignment.
