### ISSUE TITLE
use temp field in self-assignment

### ISSUE THREAD

**Issue by mbianco** [GridTools/gt4py#65]
An assignment such as:
```
a = a[J - 1]  + 2
```
has a data race. It should be transformed into
```
 tmp = a[J - 1]  + 2 ; a = tmp
```

**Comment by gronerl** [comment]
Cause of #6 

There is some more clarification needed about what the behavior should be, e.g. with conditionals: 
```Python
@gtscript.stencil
def test(f_in: dtype, f_out: dtype, flag: dtype_int):
    with computation(PARALLEL), interval(...):
        if flag:
            B = f_in
            f_out = B[1, 1, 0]
        ...
```
Runtime conditionals have to go in a single stage. This could be worked around, e.g. by expanding to  

```Python
@gtscript.stencil
def test(f_in: dtype, f_out: dtype, flag: dtype_int):
    with computation(PARALLEL), interval(...):
        if flag:
            tmp = f_in
            f_out = tmp[1, 1, 0]
        B = tmp
        ...
```
Which is very unintuitive since `B` will be written after being read, contrary to the order it is in the code in the first snippet, and most likely not what the user meant to do here. We could choose to only expand self-assignment, but even then that could cause confusion:

```Python
@gtscript.stencil
def test(f_in: dtype, f_out: dtype, flag: dtype_int):
    with computation(PARALLEL), interval(...):
        ...
        if flag:
            B = B[1, 1, 0]
            f_out = B
        ...
```
In this case, f_out would be updated to the old value of B. 

Also, this is somewhat related to my comments on #115

**Comment by mbianco** [comment]
From the discussion yesterday, IIUC, we decided to warn about this (actually this should be an error). We will think about how to allow it in case the users really want this syntax to work, but there are problems with it: an implicit synchronization at the assignment sign and/or an implicit temporary field.
Would it make sense to allow it, right now, if there are not dependencies in the horizontal?

**Comment by mbianco** [comment]
On hold until parallel model is agreed GridTools/_GT_Tasks#15

**Comment by havogt** [comment]
We decided we don't allow self assignment with shifts for now.

**Comment by havogt** [comment]
We should check if we give an error.

**Comment by jdahm** [comment]
The following code compiles without error:
```python
from gt4py import gtscript
import numpy as np


@gtscript.stencil(backend="gtc:gt:cpu_ifirst")
def stencil(
    input_field: gtscript.Field[gtscript.IJK, np.int32],
    output_field: gtscript.Field[gtscript.IJK, np.int32],
):
    with computation(PARALLEL), interval(...):
        if input_field > 0.0:
            tmp = input_field
            output_field = tmp[1, 0, 0]
        else:
            output_field = input_field
```

The gtscript parallel model splits this into three separate if conditions, and then the horizontal execution merger merges these. The generated code contains
```c++
  apply(Evaluation eval, gridtools::stencil::core::interval<
                             gridtools::stencil::core::level<0, 1, 2>,
                             gridtools::stencil::core::level<1, -1, 2>>) {
    std::int32_t tmp0;
    std::int32_t tmp1;
    bool mask_4445375937;
    bool mask_4445375938;
    mask_4445375938 =
        (static_cast<double>(eval(input_field())) > static_cast<double>(0.0));
    if (mask_4445375938) {
      tmp1 = eval(input_field());
    }

    mask_4445375937 = (static_cast<double>(eval(input_field(1, 0, 0))) >
                       static_cast<double>(0.0));
    if (mask_4445375937) {
      tmp0 = eval(input_field(1, 0, 0));
    }

    if (mask_4445375938) {
      eval(output_field()) = tmp0;
    }

    if ((!mask_4445375938)) {
      eval(output_field()) = eval(input_field());
    }
  }
```

The horizontal execution merger was applied correctly, but note that we're not doing a great job cleaning up after it: `tmp0` is written but never used. We should write a `DeadCodeElimination` pass.

**Comment by jdahm** [comment]
Also note that the following stencil causes `ParAssignStmt` validation failure, due to the self-assignment with offset.
```python
from gt4py import gtscript
import numpy as np


@gtscript.stencil(backend="gtc:gt:cpu_ifirst")
def stencil(
    input_field: gtscript.Field[gtscript.IJK, np.int32],
    output_field: gtscript.Field[gtscript.IJK, np.int32],
):
    with computation(PARALLEL), interval(...):
        if input_field > 0.0:
            tmp = input_field
            tmp = input_field + tmp[1, 0, 0]
            output_field = tmp
        else:
            output_field = input_field
```
