### ISSUE TITLE
Improve error message for non-existing backend in storage creation

### ISSUE THREAD

**Issue by leuty** [GridTools/gt4py#674]
Allocating `empty` storages works for the `cpu_ifirst` backend:

```py
from gt4py.storage import empty

ifirst_storage = empty(
    shape=(2, 2, 2),
    dtype="float64",
    default_origin=(0, 0, 0),
    backend="gtc:gt:cpu_ifirst",
)
```

but fails for the `gtc:gt:numpy` backend

```py
numpy_storage = empty(
    shape=(2, 2, 2),
    dtype="float64",
    default_origin=(0, 0, 0),
    backend="gtc:gt:numpy",
)
```

with `AttributeError: 'NoneType' object has no attribute 'storage_info'`.

**Comment by havogt** [comment]
I think there is an extra `gt` in `gtc:gt:numpy`. Should be `gtc:numpy`.

**Comment by havogt** [comment]
But obviously the error is quite bad...

**Comment by leuty** [comment]
Of course. Well, that was embarrassing.... obviously. Sorry for the noise.
