### ISSUE TITLE
Dependencies for `mypy` hook in `pre-commit`

### ISSUE THREAD

**Issue by gronerl** [GridTools/gt4py#739]
In `setup.cfg`, `mypy` is configured with `ignore_missing_imports = True` meaning that if a dependency is not found in the venv that `mypy` is installed in, type checking will not be able to assert compatibility with the types of the dependencies. 

By default, `pre-commit` does not install dependencies, meaning that also gt4py CI will not type check against dependencies.

This led the mypy pre-commit hook for me to suddenly start reporting errors when it wouldn't before after I had installed a system-wide numpy version (which recently added type hints). 

It would be beneficial to have a controlled environment for the dependencies for mypy and maybe other pre-commit hooks, at least in the CI but preferrably also locally. 

The pre-commit config does allow to specify dependency versions (https://github.com/pre-commit/pre-commit/issues/730), yet the `.pre-commit-config.yaml` would have to be overwritten in the mypy mirror.

**Comment by jdahm** [comment]
The new version of mypy bumped to in https://github.com/GridTools/gt4py/pull/978 installs stubs for dependencies. Is this what you mean?

**Comment by havogt** [comment]
we changed strategy
