### ISSUE TITLE
Division operator inside stencil performs integer floor division instead of floating point devision on cpu backends

### ISSUE THREAD

**Issue by kszenes** [GridTools/gt4py#742]
For example the code `in_field[0,0,0] = 1/2` run inside the computation context manager of a stencil will assign 0 to all elements of in_field instead of 0.5. This issue is encountered only for the cpu backends (including dace) but not for the numpy backend.

**Comment by jdahm** [comment]
Great find! This should be consistent. As a user, which would you rather see?

**Comment by havogt** [comment]
It should be Python semantics.

**Comment by jdahm** [comment]
Gridtools backends generate
```c++
...
    template<typename Evaluation>
    GT_FUNCTION static void apply(Evaluation eval, gridtools::stencil::core::interval<gridtools::stencil::core::level<0, 1, 2>, gridtools::stencil::core::level<1, -1, 2>>) {

        eval(fout()) = static_cast<double>((static_cast<std::int64_t>(1) / static_cast<std::int64_t>(2)));
    }
...
```

and the numpy backend generates
```python
        fout[i:I, j:J, k:K] = np.float64((np.int64(1) / np.int64(2)))
```

These are consistent with the IR, but have different semantics at runtime. I think it should be consistent, and it would be nice to have it follow the Python semantic (as is the guiding principle in gt4py). We'd either need to modify the upcasting rules in `gtir_upcaster.py` or add backend passes on each C++ backend. At the same time to support integer division, we'd want to add `ast.FloorDiv` support (`//`).

**Comment by gronerl** [comment]
We can either add a special case for division or leverage the utilities that numpy provides to look up proper casting rules. (or both.)

Basically, numpy provides for each ufunc (i.e. unary, binary op) a list of implementations identified by input and output types. 
E.g. for python division this is

```
>>> np.divide.types
['ee->e', 'ff->f', 'dd->d', 'gg->g', 'FF->F', 'DD->D', 'GG->G', 'mq->m', 'md->m', 'mm->d', 'OO->O']
```
We can then test our arguments to the operation with `can_cast` and each of those implementations and pick the first one where the inputs can be cast and the output type is also supported in gt4py.
 
Documentation can be found here https://numpy.org/doc/stable/user/basics.ufuncs.html?highlight=index#type-casting-rules

**Comment by jdahm** [comment]
That's a neat idea! I'm a bit confused: the numpy docs claim the character for integers is `l`, yet I don't see that in the list there. Maybe there are some implicit upcast rules too?

Regardless, this integer division rule seems to exist outside numpy even on the python interpreter level
```
>>> 1/2
0.5
```

I put up a PR that does this the simple way for now. @gronerl I'll set you as the reviewer. Feel free to go in and add commits, etc. if you'd like to try out this idea.

**Comment by gronerl** [comment]
I put up an alternative solution in #778 .
