### ISSUE TITLE
Implement differential operators as part of GTScript standard library 

### ISSUE THREAD

**Issue by tehrengruber** [GridTools/gt4py#75]
Differential operators should be implemented in one or more gtscript modules and not as builtins, to avoid an explosion of builtins in the language.

**Comment by mbianco** [comment]
Do we have the agreement that built-in functions should not have dependencies from neighbors?
Another question: will the operators be gtscript.functions?

**Comment by egparedes** [comment]
This issue only describes the idea of implementing a collection of the most common differential operators as gtscript functions (probably something like these [examples](https://github.com/GridTools/gt4py/blob/db40777788863bfe87b9674b118e8bd5b8db0440/tests/test_integration/test_suites.py#L236)). If this idea is pursued, then we should define properly: 

- the list of operators
- the gtscript standard library interface (builtin functions or builtin modules?)
- the implementation strategy

Access to neighbors is allowed in gtscript functions.

**Comment by havogt** [comment]
reopen if interest
