### ISSUE TITLE
README.md does not document requirements to run tests 

### ISSUE THREAD

**Issue by jedwards4b** [GridTools/gt4py#795]
For running tests on master the README.md does not document that you need
to run pip install -r requirements-dev.txt 
in order to run tests.

**Comment by jdahm** [comment]
Thanks for catching this and reporting! I'll get right on that...

**Comment by jdahm** [comment]
@jedwards4b Could you take a look at the linked changes and see if that makes more sense as a user? I'm happy to still rewrite it if there are other ideas you have for it.

**Comment by jedwards4b** [comment]
@jdahm  - looks better, thank you.
