### ISSUE TITLE
simple example problem

### ISSUE THREAD

**Issue by jedwards4b** [GridTools/gt4py#799]
I am attempting to run the simple example from the quick start guide,  I see the numpy backend, why isn't it working?

 python simpex.py 
Traceback (most recent call last):
  File "simpex.py", line 8, in <module>
    def stencil_example(
  File "/glade/work/jedwards/sandboxes/gt4py/src/gt4py/gtscript.py", line 276, in _decorator
    out = gt_loader.gtscript_loader(
  File "/glade/work/jedwards/sandboxes/gt4py/src/gt4py/loader.py", line 72, in gtscript_loader
    stencil_class = load_stencil("gtscript", backend, definition_func, externals, build_options)
  File "/glade/work/jedwards/sandboxes/gt4py/src/gt4py/loader.py", line 48, in load_stencil
    raise ValueError("Unknown backend name ({name})".format(name=backend_name))
ValueError: Unknown backend name (numpy)

**Comment by jedwards4b** [comment]
The backend name should be "gtc:numpy" not "numpy".

**Comment by jdahm** [comment]
The backend names were recently changed to drop the `gtc:` prefix, since the legacy backends were dropped. Could you double check that you're using the latest version? This did remind me that a few backend strings were not caught in the transition. I will make a quick change to correct that.

**Comment by jdahm** [comment]
I just checked out the latest commit, installed a virtualenv, and (after installing `matplotlib` and `jupyterlab` -- this needs to be added to the documentation somewhere) was able to run through [demo_burgers](https://github.com/GridTools/gt4py/blob/master/examples/demo_burgers.ipynb) without a problem. The `numpy` backend worked. Could you try installing again in a new virtual environment?

**Comment by jedwards4b** [comment]
Stupid git mistake - that was not the latest master.
