### ISSUE TITLE
Dynamic compilation of stencils for types found at run-time (like numba)

### ISSUE THREAD

**Issue by tehrengruber** [GridTools/gt4py#84]
Extract types of input fields at runtime and call the actual @stencil decorator with the function and the extracted types to load or compile an appropriate version of the stencil.

**Comment by jdahm** [comment]
I don't know if I quite agree with this approach. It's clearest and easiest for the user if the closure is captured at the time the stencil is parsed with `gtscript.stencil`. If dynamic types are needed, the parsing can be done at that time, right?

**Comment by havogt** [comment]
@jdahm I don't understand what you propose.

**Comment by jdahm** [comment]
I think I misunderstood the proposal at first. I'll delete my comment to avoid confusion.

**Comment by gronerl** [comment]
Do I understand this correctly that this would be similar to #990 ?

**Comment by jdahm** [comment]
Or is this more of a LazyStencil approach, but the types are not fixed at parse time, rather delayed until run time?

**Comment by jdahm** [comment]
We'll try to tackle this in the declarative version, but not here.
