### ISSUE TITLE
Proposal for gtscript region decorator 

### ISSUE THREAD

**Issue by eddie-c-davis** [GridTools/gt4py#9]
We would like your opinion on a decorator extension to GT4Py that we have been thinking about. This would mark regions that could be fused into one gtscript.stencil, so that corners and edges could be treated inside a single dawn stencil.

Example usage:

```python
@gtscript.region
def execute_code():
  stencil1(..., domain=..., origin=...)
  if cond1:
    stencil2(..., domain=..., origin=...)
  elif cond2:
    stencil3(..., domain=..., origin=...)
  for i in range(3):
    stencil4(..., domain=..., origin=...)
```

What do you think of such a feature?

**Comment by egparedes** [comment]
WIP in #24
