### ISSUE TITLE
Update code-generation to support dynamic splitters_var

### ISSUE THREAD

**Issue by tehrengruber** [GridTools/gt4py#93]
The code-generation strategy for vertical intervals should be improved automatically introducing splitters for large interval sizes. This should fix #48 and it would the first step to effectively add dynamic vertical intervals to GTScript #137

**Comment by egparedes** [comment]
The code-generation strategy for vertical intervals should be improved automatically introducing splitters for large interval sizes. This should fix #48 and it would the first step to effectively add dynamic vertical intervals to GTScript #137

**Comment by tehrengruber** [comment]
After some investigation it became apparent that this it not viable, as dynamic splitters in GridTools are introduced on the level of the entire computation, while in GT4Py the intervals are specified on the level of a stage. It is in principle possible to make this work by splitting stages in GT4Py in such a way that the intervals of the stages inside all multistages coincide, but this approach his been withdrawn: First using static splitters for interval sizes up to at least 60 has shown to be viable with tolerable increases in compile time and secondly it's not to senseful to spend more time on this given the unclear fate of the GridTools backend.

Issue #48 mentioned in the description of this issue appears to be caused by something else since the offset limit for static splitters should automatically increase and hence must be investigated seperately.

Appendix compile times for quadruple compilation of a stencil with different offset limits:

| Offset limit | Compilation time for 4 stencils |
|----------|---------------------------------|
| 2        | 20s                             |
| 20       | 34s                             |
| 50       | 61s                             |
| 60       | 71s                             |
