### ISSUE TITLE
CPU backend fails in parallel without pre-installed gridtools sources

### ISSUE THREAD

**Issue by mcgibbon** [GridTools/gt4py#937]
When I run our parallel tests using the CPU backend (probably any gridtools backend) without gridtools sources already installed, every rank tries to clone gridtools at the same time, leading to errors when earlier ranks continue on to compile code while other ranks are still deleting and overwriting those sources.

This could be fixed by importing mpi4py in a try: except block and doing MPI-parallel logic if more than one rank exists, or there may be some filesystem-based solution. If you decide this is expected behavior, we can manually clone gridtools sources on the first rank only when compiling a stencil through our wrapper layer.

**Comment by jdahm** [comment]
Oh geez this is poor behavior. Could it be fixed by git cloning to a unique temporary directory, then moving at the end back to the original location with the collision?

**Comment by egparedes** [comment]
I think the simpler solution would be to run the `gt_src_manager install` install command directly from the command line (`python -m gt4py.gt_src_manager install`) before running the MPI program. This way it is guaranteed that gridtools sources are always installed and there shouldn't be any problems.

For the future we are preparing a pip-installable version of GridTools C++ sources which will be a dependency of gt4py, so the sources will be automatically installed during gt4py installation.

**Comment by jdahm** [comment]
The best way to solve this is to use the python package for the gridtools sources. For example the effort in https://github.com/GridTools/gridtools/pull/1720.

**Comment by DropD** [comment]
> The best way to solve this is to use the python package for the gridtools sources. For example the effort in [GridTools/gridtools#1720](https://github.com/GridTools/gridtools/pull/1720).

There is one problem with that approach: (cartesian) GT4Py tests require the presence of `gridtools/tests/` sources: https://github.com/GridTools/gt4py/blob/3773fa2be4bde310e837c5d2f4b075203ccf4675/tests/reference_cpp_regression/build.py#L38 

It's probably possible to add them in the build process of the gridtools pip package, but is that the right way to do it?

**Comment by jdahm** [comment]
How large is the closure of those test headers that are in `gridtools/tests` not `gridtools/include`? It seems like it's just the `repository` and `defs` files. I would vote for just storing (copying) them in gt4py for the regression test.

**Comment by jdahm** [comment]
Now that the test will soon be removed, the linked PR should resolve this issue.
