### ISSUE TITLE
Functional: Field operator return type annotation ignored

### ISSUE THREAD

**Issue by BenWeber42** [GridTools/gt4py#945]
Here is a minimal example of a bug that abishek encountered:

```python
@field_operator
def fo_ignoring_return_type_annotation() -> Field[[CellDim, KDim], bool]:
    return broadcast(0.0, (CellDim, KDim))


@program
def program_ignoring_return_type_annotation(cell_field: Field[[CellDim, KDim], bool]):
    fo_ignoring_return_type_annotation(out=cell_field)
```

which leads to the following error message:

```console
functional.common.GTTypeError: Invalid call to function of type `(out: Field[[Cell, K], dtype=float64]) -> VoidType()`:
E     - Expected keyword argument out to be of type Field[[Cell, K], dtype=float64], but got Field[[Cell, K], dtype=bool].
```

While the example indeed contains an error, the error message is wrong. The call to `fo_ignoring_return_type_annotation` is correct.
It's the return that contains the error. The return type is annotated as `bool`, but we return a `float`.
However, gt4py will take the `return`, deduce it to be `float` and then think the field operator takes `float` as `out=`, even though  the return type is annotated as `bool`.

**Comment by tehrengruber** [comment]
The error message is very confusing, but it is not wrong. We should throw an error when defining `fo_ignoring_return_type_annotation` though, so that the user is pointed to the place where he needs to fix the issue.
