### ISSUE TITLE
Hard-coded JFrog artifactory URL

### ISSUE THREAD

**Issue by gronerl** [GridTools/gt4py#953]
Since https://github.com/GridTools/gt4py/pull/951 the URL of the JFrog artifactory is hard coded in `.gitlab-ci.yaml`. This will break if the URL changes. A more dynamic set-up would be desireable, e.g. by means of infrastructure-side updating of environment variables.

**Comment by havogt** [comment]
if this is still an issue we will see what to do when it changes...
