### ISSUE TITLE
Typing extensions 4.4 incompatible with codebase

### ISSUE THREAD

**Issue by petiaccja** [GridTools/gt4py#968]
The recent changes to *typing extensions* clash with the current codebase:
https://github.com/python/typing_extensions/blob/main/CHANGELOG.md

Type validation in eve fails due to the changes to the way typing extensions 4.4 handles `Any` and `TypeVar`.

**Comment by jdahm** [comment]
The best way to solve this is probably to update to the latest version of Eve #996.

**Comment by egparedes** [comment]
> The best way to solve this is probably to update to the latest version of Eve #996.

Not really, this is still an issue in `eve`. There is a WIP PR to fix it (#967), but it is not complete yet.

**Comment by egparedes** [comment]
Fixed in #967
