### ISSUE TITLE
Sphinx documentation should be hosted online

### ISSUE THREAD

**Issue by jdahm** [GridTools/gt4py#975]
It would be great to automatically build and push the sphinx docs to `gh_pages` when merging to `master`.

**Comment by jdahm** [comment]
We discussed this at a recent meeting and came up with the following steps:
1. Publish gt4py docs to `gt_pages`
2. Improve docs for eve and gtc
3. Create top-level sphinx page with links to all projects and switch to that.

**Comment by havogt** [comment]
Let's do this after #1040, maybe in the process we reorganize how docs are separated.

**Comment by havogt** [comment]
Docs are here https://github.com/GridTools/gt4py. Need to be updated again once we are done. Simply build the docs, copy the folder to the appropriate place in the `gh-pages` branch and push.
